### ISSUE TITLE
Close! But no cigar...

### ISSUE THREAD

**Issue by sourcesolver** [mirumee/saleor-dashboard#1007]
OK, problems with the saleor dashboard (and without the dashboard operational, this project goes nowhere fast!)

> Production
> To build the application bundle run:
> $ npm run build

* What the git omits in its instructions is that the build will appear in a "build" subfolder ("build/dashboard", to be precise...). One will have to copy the files in this folder to the root of where you are staging web server documents (and set permissions and ownership, as appropriate...)

* Now as to the build's execution: one gets a typescript version ERROR right now (_not_ a warning...) after doing an "npm update" ("Found: typescript@3.9.9...Could not resolve dependency: peerOptional typescript@"^4.2 from react-intl@5.13.2...") The build won't run to completion if that error is left unaddressed (it fails to execute a "webpack" command...) And given all the packages this product relies on, it's a given that you SHOULD do an update, to patch a number of security holes which are inevitably there.

I tried doing an upgrade in the package.json of typescript to 4.2 -good news and bad news. It gets further and is able to execute the "webpack" command, but fails out with:

> ERROR...AuthProvider.test.ts...No overload matches this call...Promise<undefined>', gave the following error... Type 'Promise<TokenAuth_tokenCreate>' is not assignable to type 'Promise<VoidOrUndefinedOnly>'...

A quick search does not indicate how to address this error; but one sees numerous other similar posts where the build script fails, and there is no guidance forthcoming from mirumee.

So while I found their architecture and approach a good and intriguing one, until they furnish a node build script (for the dashboard OR storefront...) that can be updated and runs reliably with a recent version of node (I was using 7.6.1), it's a case of a miss being as good as a mile...

**Comment by jwm0** [comment]
Hey, thanks for opening this issue. This was caused by a recent mismatch between TS version and some node versions. Node version requirements are now more strict (scoped to current LTS version) and this should get rid off all TS errors/issues. Let me know if current master solves your issue.

https://github.com/mirumee/saleor-dashboard/pull/1008

**Comment by sourcesolver** [comment]
Thank you very much for identifying this issue; I see you have updated your json dependencies, and now it warned us that the npm we were using is too new. We downgraded the npm and THEN it worked! We appear to have a build, and it loads on nginx.



On to storefront! (<joke>just after I figure out how to set up the dashboard login...</joke>)
