### ISSUE TITLE
Running server without API_URI should not be possible

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor-dashboard#102]
There is no point of running app without specified API_URI, so IMO devserver should close gracefully if no API is specified and builds should not be possible to be made. 
Currently, when you run dashboard app without API specified you are going to see this message:
 
![Screenshot 2019-08-14 at 11 46 22](https://user-images.githubusercontent.com/5188636/63012021-bd76fe80-be89-11e9-8788-4db38d8fbf30.png)

DoD:
- Attempt to build or run the server without API url should fail and present clear information to the user that configuration is missing.

**Comment by syusama** [comment]
could you please tell me how to set the API_URI?
thanks!

**Comment by JannikZed** [comment]
right now the dashboard is using `/graphql` when API_URI is not specified, right? That would be actually ok, as we want to deploy the dashbboard next to the saleor instance and make it available under the same domain. 
Just we could never get the production build running, so I don't know if it really works :D

**Comment by maarcingebala** [comment]
It's definitely a good idea and we need to get back to it.
