### ISSUE TITLE
Allow CORS

### ISSUE THREAD

**Issue by raymondfx** [mirumee/saleor-dashboard#107]
### Error
Access to fetch at 'http://localhost:8000//graphql/' from origin 'http://localhost:9000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Steps to reproduce the problem
1. "Access-Control-Allow-Origin", "*"
2. "Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept"

### What I expected to happen
…
<img width="1276" alt="Screenshot 2019-08-18 23 17 45" src="https://user-images.githubusercontent.com/26685061/63229928-703eb800-c20e-11e9-9192-af09962ae703.png">

### Screenshots

<img width="1276" alt="Screenshot 2019-08-18 22 56 58" src="https://user-images.githubusercontent.com/26685061/63229654-872fdb00-c20b-11e9-8f7b-28a13a2bbfd7.png">

**Comment by bogdal** [comment]
Saleor's GraphQL endpoint supports CORS by default, but you need to use a valid URL.

Please update your `API_URI` env variable and set
```
http://localhost:8000/graphql/
```
instead of 
```
http://localhost:8000//graphql/
```

**Comment by Batgerel53** [comment]
@raymondfx  Hello, How to fixed this error .

**Comment by omars-code** [comment]
> ### Error
> Access to fetch at 'http://localhost:8000//graphql/' from origin 'http://localhost:9000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> 
> ### Steps to reproduce the problem
> 1. "Access-Control-Allow-Origin", "*"
> 2. "Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept"
> 
> ### What I expected to happen
> … <img alt="Screenshot 2019-08-18 23 17 45" width="1276" src="https://user-images.githubusercontent.com/26685061/63229928-703eb800-c20e-11e9-9192-af09962ae703.png">
> 
> ### Screenshots
> <img alt="Screenshot 2019-08-18 22 56 58" width="1276" src="https://user-images.githubusercontent.com/26685061/63229654-872fdb00-c20b-11e9-8f7b-28a13a2bbfd7.png">

edit storefront/.env
SALEOR_API_URL=http://localhost:8000/graphql/
