### ISSUE TITLE
No feedback after fetching the tax rates

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-dashboard#113]
### What I'm trying to achieve
Fetch vatlayers tax rates.
1. Go to settings
1. Go to taxes
1. Click fetch taxes

### Describe a proposed solution
1. Add a notification "Fetching taxes..."
2. Notify "Done fetching the tax rates"

**Comment by maarcingebala** [comment]
Actually there is a success message "Successfully fetched tax rates" after the action finishes.

**Comment by NyanKiyoshi** [comment]
Cannot reproduce, thanks 👍
