### ISSUE TITLE
Saleor Errors while saving attributes 

### ISSUE THREAD

**Issue by devloperabhishek** [mirumee/saleor-dashboard#1136]
### What I'm trying to achieve
…
data should be save
### Steps to reproduce the problem
1. setup with documentation 
2.  https://docs.saleor.io/docs/developer/installation/windows### What I expected to happen
…

### Http request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

**System information**

Saleor version:
- [ ] dev (current master)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system: 
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by krzysztofwolski** [comment]
Not enough information to debug the issue - bug form not filled
