### ISSUE TITLE
Catalog > Categories > Layout overlap with the side bar.

### ISSUE THREAD

**Issue by MahmoudRizk** [mirumee/saleor-dashboard#1138]
### What I'm trying to achieve
Navigating to Product's Category.

### Steps to reproduce the problem
1. log in to the dashboard.
2. Navigate to catalog from the sidebar
3. Choose Categories.

### What I expected to happen
Nonoverlapping user interface's layout.
 
### Screenshots

![Screenshot from 2021-06-05 20-54-45](https://user-images.githubusercontent.com/10531092/120902364-4dc69a80-c640-11eb-9a4b-f689a22aa391.png)

### Console output

No Error Occurs.

**System information**

Saleor version:
- dev (current master)

Browser:
- Chrome
- Brave

**Comment by dominik-zeglen** [comment]
Fix merged in #1139
