### ISSUE TITLE
Icons are not in line on order page

### ISSUE THREAD

**Issue by mateuszkula** [mirumee/saleor-dashboard#116]
### What I'm trying to achieve
Seems that icons are not in line in order history section when reviewing order.

### What I expected to happen
I guess that icons should be in line :)

### Screenshots
![obraz](https://user-images.githubusercontent.com/30259869/63439243-fb49c900-c42d-11e9-9458-6a96358b03d1.png)

**System information**
Operating system: 
Browser:Firefox

**Comment by maarcingebala** [comment]
Seems to be fixed:
![image](https://user-images.githubusercontent.com/5421321/66126167-1db43200-e5e9-11e9-9309-827e12558487.png)
