### ISSUE TITLE
Voucher updates are broken

### ISSUE THREAD

**Issue by timuric** [mirumee/saleor-dashboard#119]
Try to create a voucher and update its values
```{"errors": [{"message": "Variable \"$input\" got invalid value {\"discountValue\": \"20\", \"discountValueType\": \"FIXED\", \"endDate\": \"2019-09-29T22:00:00.000Z\", \"name\": \"Early adopter\", \"startDate\": \"2019-08-20T22:00:00.000Z\"}.\nIn field \"startDate\": Expected type \"Date\", found \"2019-08-20T22:00:00.000Z\".\nIn field \"endDate\": Expected type \"Date\", found \"2019-09-29T22:00:00.000Z\".", "locations": [{"line": 22, "column": 24}]}]}```

**Comment by maarcingebala** [comment]
There is an issue with that in the "Sales" section but I've just tested adding/updating vouchers and seems to be working fine.

**Comment by dominik-zeglen** [comment]
Seems to be working fine with this input. I believe you were running some older core version, which used `Date` scalar defined as `YYYY-MM-DD` format, but now `startDate` and `endDate` use `DateTime` being plain ISO 8601. Please use newest saleor release and reopen this issue if problem persists.
