### ISSUE TITLE
Unable to list plugins

### ISSUE THREAD

**Issue by keanesf** [mirumee/saleor-dashboard#1196]
### What I'm trying to achieve

List plugins

### Steps to reproduce the problem
1. Login to dashboard
2. navigate to dashboard/plugins/

### What I expected to happen

That I can see list of plugins.

I have a table called plugins_pluginconfiguration that has a plugin set as active.

### Http request and response from inspector

```
[{"data": {"search": {"edges": [], "pageInfo": {"endCursor": null, "hasNextPage": false, "hasPreviousPage": false, "startCursor": null, "__typename": "PageInfo"}, "__typename": "UserCountableConnection"}}}, {"errors": [{"message": "Cannot query field \"active\" on type \"Plugin\".", "locations": [{"line": 5, "column": 3}], "extensions": {"exception": {"code": "GraphQLError", "stacktrace": ["graphql.error.base.GraphQLError: Cannot query field \"active\" on type \"Plugin\"."]}}}]}]
```

### Console output

```
dashboard.de2f2b696a0b014683a8.js?f6ef270d0029e63db592:500 POST https://api.*.com/graphql/ 400
```

**System information**

Saleor version:
- [ ] dev (current master)
- [x ] 3.0.0-a.29
- [ ] 2.11
- [ ] 2.10

Operating system: 
- [ ] Windows
- [ x] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [x ] Chrome
- [ ] Edge
- [ ] Other

**Comment by wahidkadwaikar** [comment]
If you are running the recent version of API, you may have to update the query on Plugins page and also Plugin Details page. You now get `active` variable from `PluginFragment` so try to update the query to get the information from an updated query. I'd run the following query to make the Plugin page working. You may have to remove the Channel information from the page or get that data from another sub-query.
```
fragment ConfigurationItemFragment on ConfigurationItem {
  name
  value
  type
  helpText
  label
  __typename
}

fragment PluginFragment on Plugin {
  id
  name
  description
  active
  configuration {
    ...ConfigurationItemFragment
  }
  __typename
}

query Plugins(
  $first: Int
  $after: String
  $last: Int
  $before: String
  $filter: PluginFilterInput
  $sort: PluginSortingInput
) {
  plugins(
    before: $before
    after: $after
    first: $first
    last: $last
    filter: $filter
    sortBy: $sort
  ) {
    edges {
      node {
        
        ...PluginFragment
        __typename
      }
      __typename
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
      __typename
    }
    __typename
  }
}

```

**Comment by keanesf** [comment]
I updated to saleor-dashboard-3.0.0-b.4 and saleor:3.0.0-b.4 to resolve the issue.
