### ISSUE TITLE
"Category name" table column header is mis-aligned when no categories exist

### ISSUE THREAD

**Issue by rafalp** [mirumee/saleor-dashboard#138]
### What I'm trying to achieve

...

### Steps to reproduce the problem

1. Go to categories list
2. Delete all categories

### What I expected to happen

"Category name" header to remain aligned with remaining items of the table:

### Screenshots

<img width="1287" alt="Zrzut ekranu 2019-08-28 o 19 55 43" src="https://user-images.githubusercontent.com/750553/63880345-d88b5780-c9cd-11e9-9953-c02680bb53e3.png">

**System information**
Operating system: 
Browser:

**Comment by dominik-zeglen** [comment]
Fixed some time ago
