### ISSUE TITLE
How to set API_URI in windows

### ISSUE THREAD

**Issue by syusama** [mirumee/saleor-dashboard#148]
when I install the saleor-dashboard2.0 in windows10,How can I set API_URI and APP_MOUNT_URI.And the dashboard2.0 is as a app in the saleor? How can I connection with my local saleor?thanks

**Comment by OmniOracle** [comment]
> when I install the saleor-dashboard2.0 in windows10,How can I set API_URI and APP_MOUNT_URI.And the dashboard2.0 is as a app in the saleor? How can I connection with my local saleor?thanks

So could you maybe elucidate us on which files we need to alter because I am also stuck at this stage of implementation
