### ISSUE TITLE
Quick help: Extending  Configure section of the dashboard 

### ISSUE THREAD

**Issue by Timtech4u** [mirumee/saleor-dashboard#151]
Hi @maarcingebala 

I would like to add an item that goes to an external link on the  Configure section of the dashboard.

![Screenshot from 2019-09-03 13-20-30](https://user-images.githubusercontent.com/11256481/64173526-698b8400-ce4f-11e9-9662-87046b0ad0fe.png)

I basically am not too good with React, but I believe using *a* tag  over *<Link* would work for the external link.

**Comment by maarcingebala** [comment]
@dominik-zeglen What's the suggested way of adding a link as a new tile in this section? Can you provide some example?

**Comment by dominik-zeglen** [comment]
In `src/configuration/index.tsx` you'll find `createConfigurationMenu`, which holds the whole menu structure. Just add new element to the array and it'll appear there.

**Comment by Timtech4u** [comment]
Hi @dominik-zeglen , I did just that and it builds the new in this form `http://localhost:8000/dashboard/next/configuration/https://console.mercuriemart.com`

![Screenshot from 2019-09-04 18-22-16](https://user-images.githubusercontent.com/11256481/64276959-1134af00-cf41-11e9-9248-2dff30fdb6cd.png)

**Comment by dominik-zeglen** [comment]
Oh okay, I totally forgot about that being external part.
You can add this under the `src/configuration/index.tsx:120` line:

```
<a href="https://console.mercuriemart.com">
                <Card
                  className={classes.card}
                >
                  <CardContent className={classes.cardContent}>
                    <div className={classes.icon}><YourIcon /></div>
                    <div>
                      <Typography
                        className={classes.sectionTitle}
                        color="primary"
                      >
                        Your title
                      </Typography>
                      <Typography className={classes.sectionDescription}>
                        Your description
                      </Typography>
                    </div>
                  </CardContent>
                </Card>
              </a>
```

It would require a little bit of a styling though.

**Comment by Timtech4u** [comment]
Thanks for the support @dominik-zeglen
