### ISSUE TITLE
Production-grade docker image

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor-dashboard#159]
### What I'm trying to achieve
I'm having some issues creating a production-grade docker image that makes the dashboard available under /dashboard/ - all sub components should also load from here /dashboard/dashboard.js ...etc
If someone got it already running like this I would be very interested. If more people are interested I can also add it with a pull request.

### Describe a proposed solution
My dockerfile for react apps works great like this normally:
```
# build environment
ARG APP_MOUNT_URI
ARG API_URI
ARG STATIC_URL
FROM node:12.2.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json /app/
RUN npm install
COPY . /app

RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
COPY --from=build /app/build/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
``` 
unfortunately the dashboard is available under /dashboard, but still tries to load all components directly from `/`

**Comment by NyanKiyoshi** [comment]
Can show us the nginx configuration you made/are using? And the values you set for the `API_...`

Maybe `alias` might fix the issue (http://nginx.org/en/docs/http/ngx_http_core_module.html#alias).

Or maybe `APP_MOUNT_URI` could be set to `/` and then you tell nginx to load the dashboard on `/dashboard`.

It's hard to tell without more information. Let us know!

**Comment by JannikZed** [comment]
Thank you for the answer. I got now a solution, that is working also for links like /dashboard/taxes but just for some minutes - afterwards you need to come back to /dashboard or you get forwarded to the nginx standard page. I couldn't make it with a multistage dockerfile, so I decided to build the app locally and load it into the nginx container.
`STATIC_URL=/dashboard/ APP_MOUNT_URI=/dashboard/ npm run build`
 
Dockerfile:
```
# production environment
FROM nginx:1.16.0-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
COPY ./build/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
``` 

nginx.conf:
``` 
server {

  listen 80;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  error_page   500 502 503 504  /50x.html;

  location = /50x.html {
    root   /usr/share/nginx/html;
  }

}
``` 

It's not really the best solution, but working for now. What would you recommend to change?
