### ISSUE TITLE
Redirect url is required to send a password.

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor-dashboard#162]
### What I'm trying to achieve
Creating a new user in the dashboard (Version is just some days old)

The request, that the dashboard sends looks like this: 
```
curl 'https://puYYYXXXXX/graphql/' -H ' --data-binary $'{"operationName":"StaffMemberAdd","variables":{"input":{"email":"info@XXXX.de","firstName":"Logistik","lastName":"","sendPasswordEmail":true}},"query":"fragment StaffMemberFragment on User {\\n  id\\n  email\\n  firstName\\n  isActive\\n  lastName\\n  avatar {\\n    url\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment StaffMemberDetailsFragment on User {\\n  ...StaffMemberFragment\\n  permissions {\\n    code\\n    name\\n    __typename\\n  }\\n  __typename\\n}\\n\\nmutation StaffMemberAdd($input: StaffCreateInput\u0021) {\\n  staffCreate(input: $input) {\\n    errors {\\n      field\\n      message\\n      __typename\\n    }\\n    user {\\n      ...StaffMemberDetailsFragment\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n"}' --compressed
```

The response we get looks like this:

```
{"data": {"staffCreate": {"errors": [{"field": "redirectUrl", "message": "Redirect url is required to send a password.", "__typename": "Error"}], "user": null, "__typename": "StaffCreate"}}}
```

### Screenshots
![Screenshot 2019-09-09 at 17 01 00](https://user-images.githubusercontent.com/7526174/64542451-defdc580-d323-11e9-9061-e4dc1365ae5c.png)

**System information**
Operating system: 
Browser:

**Comment by maarcingebala** [comment]
Hey, thanks for reporting! We'll try to fix it as soon as possible. Soon we'll introduce versioning in this project and then we'll be able to match backend versions with frontend ones.

**Comment by JannikZed** [comment]
versioning would be great! Or at least having a stable branch or something like this.

**Comment by JannikZed** [comment]
the exact same issue applies to createCustomer as well .. so you seem to need this redicrect URL as well @dominik-zeglen  - You might just copy your fix there as well? :)

**Comment by maarcingebala** [comment]
@JannikZed I've opened an issue about that - #204. It will require adding the ability to configure this redirect URL somewhere on the Configuration page.
