### ISSUE TITLE
Product create form doesn't fetch product types on load

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-dashboard#163]
### What I'm trying to achieve
Select a product type without typing a search keyword into the field.

### Steps to reproduce the problem
1. Go into the "create a product" form
2. Try to select a product type by clicking the dropdown
3. Nothing happens
4. Try again after having entered a search word

### What I expected to happen
Prefetched.

### Screenshots

**System information**
Operating system: Arch
Browser: Firefox 68

**Comment by dominik-zeglen** [comment]
Fixed in #189
