### ISSUE TITLE
Product create doesn't create non-existing value for dropdown attributes

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-dashboard#164]
### What I'm trying to achieve
To dynamically create values for dropdown attributes on a product creation page.

### Steps to reproduce the problem
1. Attribute with or without values
1. Go to the product creation form
1. Fill the form
1. Input a non existing value

> MyAttribute expects a value but none were given

### What I expected to happen
Having the value passed inside the variable so it would be created (note: the mutation should be able to create values dynamically--to verify)

### Screenshots

![Screenshot_2019-09-11_09-45-38](https://user-images.githubusercontent.com/6186720/64677982-eb476700-d478-11e9-9f41-4855b987392d.png)

**System information**
Operating system: Arch

Browser: FF68

**Comment by dominik-zeglen** [comment]
Must have been fixed some time ago.
