### ISSUE TITLE
Deploy Dashboard on Heroku

### ISSUE THREAD

**Issue by giovannipiccinelli** [mirumee/saleor-dashboard#174]
### What I'm trying to achieve
I am trying to deploying Dashboard module to Heroku.

### Describe a proposed solution
There should be an available clickable button "deploy to heroku" to push the project in the heroku servers just as it happens for the storefront.

### Other solutions I've tried and won't work
I  have tried installing the repo on the heroku server with github and type  the command "npm start" or "npm run build". 

### Screenshots or mockups
I get this failure page and I have no idea how to fix it. I am not a react expert unfortunately :(
![Screen Shot 2019-09-19 at 8 37 05 AM](https://user-images.githubusercontent.com/7911077/65219464-e60d9c00-dab8-11e9-9228-0899cbdf51f8.png)
![Screen Shot 2019-09-19 at 8 36 49 AM](https://user-images.githubusercontent.com/7911077/65219474-ea39b980-dab8-11e9-969e-4dd42fe3563c.png)

**Comment by NyanKiyoshi** [comment]
Might be a dumb question, but better be safe than sorry: did you run `npm install` on heroku before `npm run build`?

**Comment by giovannipiccinelli** [comment]
@NyanKiyoshi Let  me share with you here below the step by step process I followed.

1. I  have the project deployed on localhost and running well on my machine at https://localhost:3000.
2. I create a git repository to  push the code to github an auto-deploy it on Heroku.
3. I push the code to Heroku. 
4. I open the bash console  in Heroku and see the project structure `ls`
![Screen Shot 2019-09-22 at 6 28 21 PM](https://user-images.githubusercontent.com/7911077/65391237-124e4480-dd67-11e9-903f-1c79a865459c.png)
4. I then run `npm i`
![Screen Shot 2019-09-22 at 6 26 22 PM](https://user-images.githubusercontent.com/7911077/65391242-1da17000-dd67-11e9-9902-b4637481a234.png)
5. I finally run `npm start`
![Screen Shot 2019-09-22 at 6 33 23 PM](https://user-images.githubusercontent.com/7911077/65391272-96083100-dd67-11e9-81a5-0a195fc2efb3.png)

**Comment by bogdal** [comment]
@giovannipiccinelli It looks like you didn't set required `heroku-buildpacks` for your static web app:
 - https://github.com/heroku/heroku-buildpack-nodejs
 - https://github.com/heroku/heroku-buildpack-static

We have just added appropriate config files (#175) to the repo to simplify the deployment process on Heroku. The easiest way now is to re-deploy the app using `deploy to Heroku` button from the main page of this repo.

**Comment by bogdal** [comment]
I assume that the new changes solved your problem, hence I close this task.
