### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by dinhnghia** [mirumee/saleor-dashboard#176]
Please show me how to create .po translations for all languages in the locale folder.

![Screen Shot 2019-09-24 at 12 37 00 AM](https://user-images.githubusercontent.com/13850307/65448895-072d0e80-de64-11e9-8b8f-6bba810050ea.png)

Translate to 

![Screen Shot 2019-09-24 at 12 41 52 AM](https://user-images.githubusercontent.com/13850307/65448935-2035bf80-de64-11e9-9fc3-fd80e504a412.png)

I tried running the npm run extract-messages command but it only created the messages.pot file. But I want it to create files ar.po, az.po, en.po, etc.

**Comment by dinhnghia** [comment]
@dominik-zeglen @benekex2 @maarcingebala @bogdal @patrys @likewhoa @dankolbman
Please help me

**Comment by dominik-zeglen** [comment]
Could you describe what are you trying to achieve? Do you want to update your `.po` files with new messages? I can't help you if I don't know what is your problem.  
And please, next time use issue template.

**Comment by dinhnghia** [comment]
@dominik-zeglen thanks. I want to update my .po files.

**Comment by dominik-zeglen** [comment]
You need to use external tool like [poedit](https://poedit.net/) or [transifex](https://www.transifex.com/) to update `.po` files using `.pot`.

**Comment by dinhnghia** [comment]
Thanks so much.
