### ISSUE TITLE
Product Description does not update.

### ISSUE THREAD

**Issue by CelesteComet** [mirumee/saleor-dashboard#187]
### What I'm trying to achieve
I'm trying to update my product with a description but it won't update. 

### Steps to reproduce the problem
1. Use saleor dashboard 2.0
2. Input a description for a product and hit save.
3. Check the local site and see that the description has not updated.

### What I expected to happen
Description should be updated with what is input in saleor dashboard 2.0

**System information**
Operating system: Mac OS
Browser: Chrome

**Comment by NyanKiyoshi** [comment]
Hi! By local site, you mean the non-PWA one? If so, you need to set the `USE_JSON` setting to `True`.
