### ISSUE TITLE
Extend models with metadata

### ISSUE THREAD

**Issue by peekeesrl** [mirumee/saleor-dashboard#195]
### What I'm trying to achieve
I would like to extend the ProductVariant with metadata, for example by adding an additional description.

### Describe a proposed solution
I think I would need an input field where I could paste some JSON. Please tell me if I am missing the purpose of metadata and private_metadata.

This could be easily queried and displayed on Storefront 2.0.

Thanks in advance.

**Comment by maarcingebala** [comment]
Hey! Meta fields were implemented with API in mind, therefore all models that support them have mutations to set or clear the meta fields. The idea is that you can use them to store any data from a third-party integration talking to Saleor API. We're also using them internally with the plugin architecture or payment gateways. We haven't thought about implementing any UI for that.

**Comment by peekeesrl** [comment]
@maarcingebala Thank you for the reply!

For instance, for the example of the description of the ProductVariant, I could use ProductVariantUpdateMeta.

What about implementing a component where we could paste plain JSON? This should be validated before being saved. The frontend (which needs to be customised for the particular case) will display the additional information if present and depending for example also on the product type.

This could be way a simple and fast way to extend a model without touching the models.py files and the database.

Let me know what you think!

**Comment by tejpochiraju** [comment]
@peekeesrl We are about to migrate from the previous Django dashboard to the React dashboard to be able to implement this particular use case. I was planning to creating a fork of the saleor-dashboard code and adding our custom functionality in the UI. A couple of comments/questions:

1. While what you are suggesting is a more generic way to implement this, I am wondering if the UX for the shop admin is good enough if it's just a JSON field.
2. In terms of validation, wouldn't the validation necessarily be use-case specific? How would a generic component help in this case?

We expect to start implementing these next week so will post an update on our choices. In the meantime, if there are generic components we could contribute then happy to listen!

**Comment by timuric** [comment]
Most webshops have various product descriptions, such as "Specs", "Features", size charts etc. At the moment you need to use additional CMS system with Saleor in order to populate such content. Having metadata editor is a powerful addition that can cover lots of use cases. 

Besides product descriptions I would like to use metadata editor to manage pricing for various currencies, which is also a very common use case.

Please let me know if you are open to a pull request.

**Comment by maarcingebala** [comment]
@timuric What about product attributes? You could use them to store custom fields such as specs or features. For different currencies we want to have dedicated support in the multichannel feature that we'll soon start working on.

The idea of metadata was to be consumed by APIs/integrations, while attributes are used for things visible in the interface. Currently only products have attributes but our roadmap also includes having user and order attributes.

**Comment by timuric** [comment]
@maarcingebala Product attributes are meant serve for reusable and finite options, where is metadata can be something flexible and unique to each product. 

For example our website stores json files for products separately to display various info as such:
![image](https://user-images.githubusercontent.com/4006792/82830083-13ff7780-9eb5-11ea-973d-8d6bceef30e8.png)

Unfortunately attributes are not a really good fit for such content.

**Comment by heathwinning** [comment]
I also have need for product attributes that can take arbitrary values. Three examples that are forefront to me migrating to Saleor are:
* date/year that an individual product was created (the products are artworks),
* links to blog posts or videos that features the product (an attribute that allows list values would be nice for multiple links),
* arbitrary dimensions, which is especially important for one-of-a-kind products whose sizes can varying greatly.

**Comment by stevekrasinsky** [comment]
This is a super helpful post with an answer to what I imagine is a very common issue. Thanks everyone!

**Comment by timuric** [comment]
@stevekrasinsky FYI Metadata editor was added in Saleor 3

**Comment by stevekrasinsky** [comment]
> @stevekrasinsky FYI Metadata editor was added in Saleor 3

In the dashboard? Thx @timuric

**Comment by timuric** [comment]
> > @stevekrasinsky FYI Metadata editor was added in Saleor 3
> 
> In the dashboard? Thx @timuric

Yep

**Comment by stevekrasinsky** [comment]
@timuric saw that. Thank you for the reply

**Comment by stevekrasinsky** [comment]
Hey @timuric any advice on getting the metadata information into the ProductTile? I realize that changing the Product interface is a bit of a nightmare & probably not the way to go.
