### ISSUE TITLE
Improvements in draft/regular order details view

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-dashboard#196]
There is a bunch of changes to do in both order details views.

Only draft order details:
- [x] ability to add a discount 

Both views:
- [x] Show product's SKU for each order line
- [x] Add the "Shipping carrier" card with the ability to add or change the shipping information.
- [x] Display "Notes" card with the ability to add or change notes from customers.

I'm not sure if API for all those changes is in place; we'll have to add it before we start working on this.

**Comment by maarcingebala** [comment]
- [ ] 🐛 :
![image](https://user-images.githubusercontent.com/5421321/66126104-ee052a00-e5e8-11e9-8e4c-b96e270bd0f8.png)

**Comment by eCzerniak** [comment]
![image](https://user-images.githubusercontent.com/29308910/132004534-2406e55b-0c69-4a70-9a94-d01028eb1458.png)
