### ISSUE TITLE
Deploy saleor-dashboard to server centos 7 with nginx

### ISSUE THREAD

**Issue by xuanmaithanh** [mirumee/saleor-dashboard#198]
### What I'm trying to achieve
I want to deploy saleor-dashboard to my server (the Centos 7 OS) with using nginx

### Steps to reproduce the problem
1. install git and git clone the project
2. npm i & npm run build -> can see `build/dashboard/index.html` and other files related
3. config DNS (on cloudflare) to point to the server
4. Install nginx, modify nginx.conf to point to the folder and index.html

See error when  access the browser on local PC
`500 Internal Server Error
nginx/1.12.2`

### What I expected to happen
Can deploy the project, access on browser and see it works

### Screenshots
nginx.conf
![image](https://user-images.githubusercontent.com/31360157/66202368-c9d04880-e6cf-11e9-868c-41f6f56f5462.png)

the error when access on browser
![image](https://user-images.githubusercontent.com/31360157/66202531-2d5a7600-e6d0-11e9-9916-fb23c25eb77a.png)

the saleor-dashboard on server
![image](https://user-images.githubusercontent.com/31360157/66202766-bc678e00-e6d0-11e9-8474-6d9937142cdc.png)

view index.html
![image](https://user-images.githubusercontent.com/31360157/66202792-d30de500-e6d0-11e9-9d32-9671ae7a744d.png)

**Comment by dominik-zeglen** [comment]
I know some time passed by, but today we merged #235 which gives you dockerfile with configured nginx. Hope it helps.
