### ISSUE TITLE
Deploying to e.g. /dashboard/ requires use of undocumented STATIC_URL

### ISSUE THREAD

**Issue by raoz** [mirumee/saleor-dashboard#199]
### What I'm trying to achieve
Deploy saleor-dashboard to /dashboard/, such that it be self-contained

### Steps to reproduce the problem
1. Set APP_MOUNT_URI=/dashboard/
2. Set appropriate API_URI
3. `npm run build`
4. Copy files to directory which is served by nginx to /dashboard/
5. Navigate to /dashboard/

### What I expected to happen
To have a working dashboard, but instead I get 404s for the bundle etc.

### Workaround
Set STATIC_URL to /dashboard/. 

### Proposed fix
Either document STATIC_URL in README or make webpack config use APP_MOUNT_URI  instead of STATIC_URL (the latter possibly breaks existing configs?).

**Comment by JannikZed** [comment]
related: #159 
same issue with Nginx .. I solved it the same way as you. But in the end, it's not perfect, or at least I don't know how to get it perfectly working with Nginx - what config do you use there? Can you go back and forth in your browser without coming to the Nginx standard webpage?

**Comment by raoz** [comment]
> same issue with Nginx .. I solved it the same way as you. But in the end, it's not perfect, or at least I don't know how to get it perfectly working with Nginx - what config do you use there? Can you go back and forth in your browser without coming to the Nginx standard webpage?

My nginx config is essentially
```
location /dashboard/ {
		root /srv/;
		index index.html;
		try_files $uri $uri/ /dashboard/index.html;
	}
```

I set STATIC_URL=/dashboard/ and APP_MOUNT_URI=/dashboard/. During experimentation I also set homepage in package.json to "https://mysite/dashboard", but I'm not sure if that actually did anything.

With this config, I don't have the issue you describe.
