### ISSUE TITLE
Unable to start or build saleor-dashboard

### ISSUE THREAD

**Issue by Timtech4u** [mirumee/saleor-dashboard#2]
![Screenshot from 2019-07-31 19-54-14](https://user-images.githubusercontent.com/11256481/62239642-3035a380-b3cd-11e9-8ac4-5a7989da9cd3.png)

I get the error above when I try to start saleor-dashboard locally.
I have set the API_URL correctly but still can't figure out what's wrong.
cc: @maarcingebala

**Comment by bogdal** [comment]
@Timtech4u make sure that you have installed all the project's dependencies:
```
npm i
```

**Comment by Timtech4u** [comment]
![Screenshot from 2019-07-31 21-47-47](https://user-images.githubusercontent.com/11256481/62247469-cd003d00-b3dd-11e9-8c85-5678ed5e46ba.png)

Same issue, works when I forcefully install.
```
npm i -f
```

However, `npm run build` or `npm run start` gives the same error as earlier reported.

**Comment by bogdal** [comment]
What does the log file say? Try to remove the `node_modules` dir and install dependencies from the beginning.

**Comment by maarcingebala** [comment]
What Node and NPM versions are you using? We require Node > 10.x.

**Comment by Timtech4u** [comment]
Hi @maarcingebala , I make use of **Node v10.15.2** and **Npm v6.10.0**

I have attempted removing `node_modules` but it doesn't fix.

I might have to stick to Saleor's Dashboard for now :+1:

**Comment by AlexandrST** [comment]
npm -i -g 
after
npm link webpack 

it helped me, the error was similar!

**Comment by dvska** [comment]
the same problem here, 
fresh install @ macOS Mojave, Node v15.3.0.

npm i -g
npm link webpack

haven't helped

> saleor-dashboard@3.0.0-a.0 start
> webpack-dev-server -d

sh: webpack-dev-server: command not found
