### ISSUE TITLE
IMPROVEMENT vol. 6

### ISSUE THREAD

**Issue by pwgryglak** [mirumee/saleor-dashboard#203]
- [x] modals "Cancel" button should be changed to "Back" @timcla 
- [x] in Variant creator buttons should be called "Cancel" "Previous" and "Next"
- [x] "Cancel" button on pages should be renamed to "Back"
- [x] on order cancellation modal cancel confirmation button should be named "Cancel Order"

**Comment by timcla** [comment]
And 'Remove' in the footers, should be changed as well?

**Comment by pwgryglak** [comment]
@timcla 
It was changed already in he newest version of the dashboard
