### ISSUE TITLE
Role permission restrictions can't be updated

### ISSUE THREAD

**Issue by giovannipiccinelli** [mirumee/saleor-dashboard#208]
### What I'm trying to achieve
I am trying to restrict a user to certain permissions.

### Steps to reproduce the problem
1.  Pull latest dashboard and core versions.
2. From home Navigate to Settings > Staff Members > "User" > Permissions
3. Uncheck "user has full access to the store". Uncheck specific permissions (i.e. I unchecked the first 2 permissions)
4. Save

### What I expected to happen
When I refresh the page the user appears to have full permissions while I removed 2 permissions.

### Screenshots
![Screen Shot 2019-10-10 at 8 25 59 PM](https://user-images.githubusercontent.com/7911077/66595970-50879880-eb9c-11e9-8371-27347864a3e6.png)
![Screen Shot 2019-10-10 at 8 26 19 PM](https://user-images.githubusercontent.com/7911077/66595982-554c4c80-eb9c-11e9-812e-93a7f0dbba97.png)

**System information**
Operating system: Heroku
Browser: Chrome

**Comment by dominik-zeglen** [comment]
You probably tried to change superadmin's permissions, which is not going to work. But it seems that UI should indicate that this user is superadmin.

**Comment by giovannipiccinelli** [comment]
@dominik-zeglen this is possible. The main issue is I can't invite new staff users to the application from the dashboard interface. It trows back an error. 

<img width="790" alt="Screen Shot 2019-10-13 at 11 56 07 AM" src="https://user-images.githubusercontent.com/7911077/66713931-87ce9300-edb0-11e9-83c8-4a5644d7a170.png">

Maybe there is something wrong with my email configuration. However it looks ok to me. 

{'EMAIL_FILE_PATH': '', 'EMAIL_HOST_USER': 'xxxxxxxx@gmail.com', 'EMAIL_HOST_PASSWORD': 'xxxxxxxx', 'EMAIL_HOST': 'smtp.gmail.com', 'EMAIL_PORT': 587, 'EMAIL_USE_SSL': True, 'EMAIL_USE_TLS': False, 'EMAIL_BACKEND': 'django.core.mail.backends.smtp.EmailBackend'}

**Comment by dominik-zeglen** [comment]
Can you post error that comes from the API?

**Comment by giovannipiccinelli** [comment]
it seems a permission issue. But this is quite surprising given that I am using a "SUPERUSER" account. Check it out below.

![Screen Shot 2019-10-16 at 7 17 36 PM](https://user-images.githubusercontent.com/7911077/66942766-0e51d180-f04a-11e9-838e-591581d71e11.png)

Is  the API suppose to trigger a notification email if successful?

**Comment by dominik-zeglen** [comment]
Yes.
It seems that dashboard is doing okay and the problem lies within the core. Which version do you use (release/hash of the last commit)?

**Comment by giovannipiccinelli** [comment]
@dominik-zeglen I pulled the latest commits of core, dashboard and storefront. Email is still not working I get the ERR above.

**Comment by dominik-zeglen** [comment]
Go to the 'network' tab in browser's inspector, find the request with this mutation and post response here, we'll see what's happening here 🤷‍♂️

**Comment by giovannipiccinelli** [comment]
My fault.. looks I did not set ALLOWED_HOST variable in the environment with the correct subdomain. Thanks!
