### ISSUE TITLE
Browser navigation in some places broken

### ISSUE THREAD

**Issue by raoz** [mirumee/saleor-dashboard#214]
### What I'm trying to achieve
Move around the dashboard using standard browser tools, i.e. the forward and back buttons

### Steps to reproduce the problem
1. Go to Catalog>Products (e.g. http://localhost:9000/products)
2. Click on a product
3. Go back to the products view using the browser ← button
4. I cannot go to the product I had selected using the →button (I believe that `products/?asc=true&sort=name` gets pushed to the history stack)

### What I expected to happen
To be able to go to the product I had selected using the browser's builtin forward button.

**System information**
Operating system: Arch Linux
Browser: Chromium 77

**Comment by dominik-zeglen** [comment]
Oops, that's on me.
