### ISSUE TITLE
Allow uploading multiple images at a time

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor-dashboard#241]
### What I'm trying to achieve
Upload multiple product images at a time, either through drag and drop or the file explorer. The new dashboard currently does not allow that. Even if multiple images are dropped into the widget, only 1 is uploaded.

### Describe a proposed solution
The old dashboard allowed uploading multiple product images in one go. That would be useful to have in this dashboard as well.

**Comment by maarcingebala** [comment]
Hey, we'll look into this. API supports uploading files one by one, but I think it would make sense it the context of image upload to send each file in a separate mutation.

**Comment by khalibloo** [comment]
I agree, keeping each upload as a separate mutation would make it easier to handle errors too. An error in one wouldn't cause all the uploads to fail. It should be up to the UI to queue the uploads.
