### ISSUE TITLE
Image upload replaces other products images

### ISSUE THREAD

**Issue by Timtech4u** [mirumee/saleor-dashboard#266]
Hi @maarcingebala , I am working on an entirely new Dashboard for the Saleor API.

When I add new product images, it replaces the existing product images on the backend and also for other products.

I have check how it's done on the Saleor Dashboard and I am sure my mutations are correct. Would like to know if there's some way to find out what's wrong. Thanks

**Comment by maarcingebala** [comment]
Hey, we need more information to help you. Can you share the GraphQL mutations that you use to add images? Any piece of code/queries will help us to better understand your use-case.

**Comment by enkaypeter** [comment]
Hi @maarcingebala below is the mutation:
```
        ...
        const {fileBlob, fileObj}  = file; // fileBlob is an image converted to blob datatype
        let fileData = new File([fileBlob], fileObj.name); //converting fileBlob to file datatype

        await this.$apollo.mutate({
          mutation: gql`
            mutation createProductImage($image: Upload!, $product: ID!) {
              productImageCreate(input: { image: $image, product: $product }) {
                image {
                  id
                }
              }
            }
          `,
          variables: {
            image: fileBlob,
            product: prodId
          },

        });


```

When tried with blob datatype, product images are replaced with incoming images. When tried with  file datatype (fileData) the response returned is as follows; 

`{"data": {"productImageCreate": {"image": null, "__typename": "ProductImageCreate"}}}`

**Comment by dominik-zeglen** [comment]
The current flow is:
1. Get a mutation with `Upload` input type
2. Get a `<input type="file" />`
3. Grab input's `.files` value
4. Any element of this array can be used as an argument in mutation

**Comment by dominik-zeglen** [comment]
Oh, be sure to use `apollo-upload-client`, it simplifies things a lot.

**Comment by Timtech4u** [comment]
Thanks for the help @dominik-zeglen
