### ISSUE TITLE
Make UI feedback messages better noticeable

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-dashboard#268]
After testing various flows in the dashboard we noticed that sometimes the feedback messages (notifying users about success or failiure of an action) are not so easy to notice. Some actions are saved instantly (e.g. the switch "Product type uses Variant Attributes" on the screenshot below). When working on a desktop screen and focusing on the bottom part of the screen, the message "Saved changes" is easy to overlook, which leads to confusion whether the action was actually saved.

We should think whan can we do to make it more visible, eg. by using dark background, place it in a different position or show it a bit longer.

![Screenshot 2019-11-25 at 10 48 20](https://user-images.githubusercontent.com/5421321/69530186-e96a4b80-0f71-11ea-99c6-6046f1a0183c.png)

**Comment by pwgryglak** [comment]
It's done. You can see that in project.

**Comment by maarcingebala** [comment]
Cool, thanks.

**Comment by krzysztofwolski** [comment]
New notification system is already implemented.
