### ISSUE TITLE
Design for Saleor extensions

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-dashboard#279]
We're building Saleor Marketplace for apps/extensions. These apps will provide their own UI that we want to display inside our dashbaord. We need a design for this "Extensions" section where users will see the list of enabled apps and will be able to open UI provided by this apps (embedded in our dashboard in an iframe).

**Comment by pwgryglak** [comment]
@maarcingebala 
to be reviewed on designs. Waiting for feedback
