### ISSUE TITLE
Failing to fetch the vat layer taxes doesn't trigger any feedback

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-dashboard#284]
### Steps to reproduce the problem
1. In remove the vatlayer access key
1. Go under settings
1. Taxes
1. Click 'Fetch taxes'
1. It should show nothing at all, as it nothing happened

```json
{"data":{"shopFetchTaxRates":{"errors":[{"field":null,"message":"Could not fetch tax rates. Make sure you have supplied a valid API Access Key.","__typename":"Error"}],"shop":null,"__typename":"ShopFetchTaxRates"}}}
```

### What I expected to happen
Have a notification box with the error message.

**System information**
Browser: Firefox 70

**Comment by gax97** [comment]
Does anyone have an idea of what is going on with this problem?

**Comment by eCzerniak** [comment]
At 3.0 version it is not possible to clear access key without setting this plugin as inactive. I'm closing this ticket.
