### ISSUE TITLE
Dashboard 'Pages' and 'Navigation' not working properly

### ISSUE THREAD

**Issue by r-zammit** [mirumee/saleor-dashboard#324]
### What I'm trying to achieve
Add a child Page to the navber in "Pages" and "Navigation" in the Configuration section. 
There are 2 problems:
1. The content of the page doesn't show up, it's just a blank section
2. The navigation element never appears as a child, even though it's indented in the UI as a child, like it's described in the documentation

### Steps to reproduce the problem
1. Simply add a Page with content and try to add a child navigation. Doesn't work.

**System information**
Operating system: MacOS
Browser: Chrome + Safari (Tried both)

**Comment by karolkielecki** [comment]
@r-zammit Hi there! Apologies for the delayed response. Could you please tell me which version of Saleor are you using?
