### ISSUE TITLE
on windows 10 using cmd how i can set api uri? i don't understand somebody can help me please

### ISSUE THREAD

**Issue by valentinc94** [mirumee/saleor-dashboard#348]
### What I'm trying to achieve
…

### Describe a proposed solution
...

### Other solutions I've tried and won't work
…

**Comment by karolkielecki** [comment]
@valentinc94 Hey! If you install Ubuntu, using cmd should be easier for you: https://www.microsoft.com/pl-pl/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab

You can find more details on how to setup API_URI here: https://github.com/mirumee/saleor-dashboard#getting-started

If you have more questions, let me know.

**Comment by benmandakh2609** [comment]
Did you solve it? I have same issue

**Comment by maarcingebala** [comment]
Please read about setting environment variables on Windows. You need to do that in the terminal where you're running your Saleor Dashboard app: https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt/79614
