### ISSUE TITLE
Uploaded images are not resized to thumbnails

### ISSUE THREAD

**Issue by raylooi** [mirumee/saleor-dashboard#349]
anyone encountering the same issue? 

### What I'm trying to achieve
Upload images for products in Dashboard

### Steps to reproduce the problem
1. Dashboard was deployed using one-button deployment to Heroku. 

### What I expected to happen
Images are resized so that thumbnails are seen in the product listing page

### Screenshots
![dashboard](https://user-images.githubusercontent.com/42400783/71878571-e5336f80-3166-11ea-8f26-23ae06204e2b.jpg)

**System information**
Operating system: Heroku Linux
Browser: Firefox

**Comment by karolkielecki** [comment]
@raylooi Hey. Could you please tell us more details? Which version of Saleor are you using? Which image format do you use?

**Comment by raylooi** [comment]
this version:
https://github.com/mirumee/saleor-dashboard

i have tried both .jpeg and .png.

**Comment by maarcingebala** [comment]
@raylooi Does it work for you if you run the app locally (not on Heroku)? In Heroku you need to additionally configure S3 bucket to store media files. By default in the free plan, the storage is cleared regularly: https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem
