### ISSUE TITLE
[VARIANT CREATOR] Blank page product for variants with more then 2 attributes

### ISSUE THREAD

**Issue by tboulogne** [mirumee/saleor-dashboard#350]
### What I'm trying to achieve
Create product variants with 3 attributes with variant creator

### Steps to reproduce the problem
1. Create a product type with 3 attributes
2. Use variant creator to create variants with this 3 attributes

### What I expected to happen
Product available on page, but get blank page.

If i manually create variants it works. Just have 2 dropdown with one including 2 attributes.

Thanks for help on this.

Regards

**Comment by maarcingebala** [comment]
You mean you're getting a blank page in the storefront? If yes, then we have a open PR for that that will be soon merged: https://github.com/mirumee/saleor-storefront/pull/550

**Comment by maarcingebala** [comment]
See this issue: https://github.com/mirumee/saleor-storefront/issues/514. If this is what you mean then we can close this one.

**Comment by tboulogne** [comment]
@maarcingebala Thanks for your reply.

Yes i get a blank page on storefront if product get 3 attributes and variants was created from variants creator.

If i manually create a product with 3 attributes. It works. (on storefront, i have 2 select dropdowns with one combining 2 attributes).

**Comment by tboulogne** [comment]
> You mean you're getting a blank page in the storefront? If yes, then we have a open PR for that that will be soon merged: [mirumee/saleor-storefront#550](https://github.com/mirumee/saleor-storefront/pull/550)

will be soon merged ? mean today :-)

**Comment by maarcingebala** [comment]
Depends if there are any changes requested in the code review. Can't promise anything but I would also love to merge this today/tomorrow.

**Comment by tboulogne** [comment]
It will be really GREAT :-) !!!!

**Comment by maarcingebala** [comment]
I'm closing this since we already have an issue for that in `saleor-storefront` repo.

**Comment by tboulogne** [comment]
Hello @maarcingebala. Are you ready to merge ;-) ? It could help. thanks
