### ISSUE TITLE
Saleor runs into unexpected problem

### ISSUE THREAD

**Issue by gComet** [mirumee/saleor-dashboard#355]
### What I'm trying to achieve
Login to dashboard

### Steps to reproduce the problem
1. Giving 405 error when I try to login

### What I expected to happen
To login ofc

### Screenshots

**System information**
Operating system:  Ubuntu
Browser: CHrome

I have changed the API_URI in app.js but nothing is happening

Here is in console headers, it's taking 9000 port, why?

Request URL: http://localhost:9000/graphql/
Request Method: POST
Status Code: 405 Method Not Allowed
Remote Address: 127.0.0.1:9000
Referrer Policy: no-referrer-when-downgrade

**Comment by karolkielecki** [comment]
@gComet Hey. Please take a look at our configuration guidance: https://github.com/mirumee/saleor-dashboard#configuration If you have any questions, let me know.

**Comment by Lifechess** [comment]
I have the same problem  Code: 405 Method Not Allowed
i cant login in to dashboard and i can do it in storefront

**Comment by infinitecipher** [comment]
@gComet @Lifechess just add .env file with those variables and it should work.

**Comment by maarcingebala** [comment]
Please check if you have `API_URI` env variable set and the app is actually connected to the API. You can inspect that as well in the Network tab in your browser's dev tools - just look for `/graphql` requests and see if they're successful.

**Comment by Lifechess** [comment]
I find the problem in config.ts i forgot to export APPI_URI AND APP_MOUNT_URI
