### ISSUE TITLE
Unexpected Error when logging in

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor-dashboard#369]
### What I'm trying to achieve
Log in to dashboard using any staff account other than the first staff account (admin@example.com) in a test app.

### Steps to reproduce the problem
1. Try to log in with a non-default staff account

### What I expected to happen
I expected to be able to log in. I get a generic error message. On inspecting the console, I see that gql is returning "'account.impersonate_users' is not a valid PermissionEnum". admin@example.com can log in, but not the other staff accounts.

**System information**
Operating system: Windows 10 x64
Browser: Firefox 72

**Comment by maarcingebala** [comment]
Thanks for reporting. It seems like a bug - we've dropped this permission some time ago since it's not used in Saleor anymore. @dominik-zeglen I thought errors like this should be caught by Typescript when we have up-to-date types? Or maybe we had an obsolete schema here?

**Comment by khalibloo** [comment]
Yeah it seems the schemas are out of sync. The dashboard schema still has IMPERSONATE_USERS among its permissions.
