### ISSUE TITLE
Dashboard crashes when viewing staff details

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor-dashboard#370]
### What I'm trying to achieve
View staff details page, or create new staff member.

### Steps to reproduce the problem
1. Open a staff page or invite new staff.

### What I expected to happen
To see staff details. This works fine for the default admin, admin@example.com in this case. But crashes with any other staff account.

Edit:
This appears to be linked to #369. There is a gql error in the console "'account.impersonate_users' is not a valid PermissionEnum".

**System information**
Operating system: Windows 10 x64
Browser: Firefox 72

**Comment by khalibloo** [comment]
The gql schemas are out of sync. https://github.com/mirumee/saleor/blob/master/saleor/graphql/schema.graphql and https://github.com/mirumee/saleor-dashboard/blob/master/schema.graphql don't match up.

**Comment by khalibloo** [comment]
Could you please check this again? I'm still getting the same error even after a fresh install of the dashboard.  Weirdly enough, I can't find `impersonate` anywhere in the dashboard code.
It appears to be coming from the saleor core database. The row for `impersonate_users` is still included under the `auth_permission` table.

That explains why the error does not affect my superuser. It only affects users that were created and assigned the `impersonate_users` permission before it was removed from saleor. I would think the migrations would have taken care of this.

**Comment by dominik-zeglen** [comment]
Can't reproduce this. Can you post `data` of the query that feeds staff details view?
It might be helpful to decide whether it's a dashboard or core problem.

**Comment by khalibloo** [comment]
Yeah it looks like a core problem. Manually deleting the association between a staff user and the impersonate permission fixes the problem for that staff user. Here is the API response.
```json
{
  "0": {
    "errors": [
      {
        "message": "'account.impersonate_users' is not a valid PermissionEnum",
        "locations": [
          {
            "line": 16,
            "column": 3
          }
        ],
        "path": [
          "user",
          "permissions"
        ],
        "extensions": {
          "exception": {
            "code": "ValueError"
          }
        }
      }
    ],
    "data": {
      "user": {
        "id": "VXNlcjo2",
        "email": "mario@example.com",
        "firstName": "Super",
        "isActive": true,
        "lastName": "Mario",
        "avatar": {
          "url": "https://sample.s3.amazonaws.com/user-avatars/avatar6.png",
          "__typename": "Image"
        },
        "__typename": "User",
        "permissions": null
      }
    }
  }
}

```

**Comment by karolkielecki** [comment]
@khalibloo Thank you for the details. We're working to fix it.
