### ISSUE TITLE
Add SKU Column to order details.

### ISSUE THREAD

**Issue by tboulogne** [mirumee/saleor-dashboard#371]
### What I'm trying to achieve
Make différence on variant products into order détails.

### Describe a proposed solution
Ad a SKU column.

### Screenshots or mockups
![image](https://user-images.githubusercontent.com/6205275/72349579-0ce18500-36dd-11ea-8a60-61395cda3ce5.png)

Thanks

**Comment by karolkielecki** [comment]
@tboulogne Hi there! We appreciate your feedback. We'll discuss it. 
Best

**Comment by krzysztofwolski** [comment]
Could be also in 2line of product name

**Comment by tboulogne** [comment]
@krzysztofwolski into the product list ?

**Comment by tboulogne** [comment]
@karolkielecki 
@krzysztofwolski 

hello a little UP on this :-)

**Comment by maarcingebala** [comment]
We need to prepare some design for this change and introduce it consistently in a few more views in the dashboard.

**Comment by tboulogne** [comment]
@maarcingebala thanks for reply.
any schedule on this :-) please ?

**Comment by maarcingebala** [comment]
I can't promise any dates, there is a lot of ongoing work and priorities agreed on earlier. It depends on our internal planning.

**Comment by tboulogne** [comment]
ok thanks :-)

**Comment by krzysztofwolski** [comment]
![image](https://user-images.githubusercontent.com/5188636/99256929-78711300-2816-11eb-9319-f7bb8617b6c0.png)

**Comment by tboulogne** [comment]
great ! thanks
