### ISSUE TITLE
 Uncaught TypeError: listElements.find is not a function

### ISSUE THREAD

**Issue by joelunmsm2003** [mirumee/saleor-dashboard#372]
I get this error

Oops! ...
ERROR
We have encountered a problem ...
Do not worry everything will be fine

When you want to publish a product, you can help me

useListActions.ts?a324:10 Uncaught TypeError: listElements.find is not a function
    at isSelected (useListActions.ts?a324:10)
    at eval (ProductList.tsx?1700:276)
    at Array.map (<anonymous>)
    at renderCollection (misc.ts?702e:52)
    at ProductList (ProductList.tsx?1700:259)
    at renderWithHooks (react-dom.development.js?61bb:16241)
    at updateFunctionComponent (react-dom.development.js?61bb:18328)
    at beginWork$1 (react-dom.development.js?61bb:20151)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:385)

react-dom.development.js?61bb:21810 The above error occurred in the <ProductList> component:
    in ProductList (created by ProductListPage)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Card))
    in ForwardRef(Card) (created by WithStyles(ForwardRef(Card)))
    in WithStyles(ForwardRef(Card)) (created by ProductListPage)
    in div (created by Container)
    in Container (created by ProductListPage)
    in ProductListPage (created by Mutation)
    in Mutation
    in Unknown (created by Mutation)
    in Mutation
    in Unknown (created by Query)
    in QueryProgress (created by Query)
    in Query
    in Unknown (created by Query)
    in Query
    in Unknown (created by ProductList)
    in ProductList (created by ProductList)
    in ProductList (created by Context.Consumer)
    in Route (created by Component)
    in Switch (created by Component)
    in Component (created by Context.Consumer)
    in Route (created by Route)
    in Route (created by AuthProvider)
    in Switch (created by AuthProvider)
    in ErrorBoundary (created by AuthProvider)
    in main (created by AppLayout)
    in div (created by AppLayout)
    in div (created by AppLayout)
    in div (created by AppLayout)
    in AppLayout (created by AuthProvider)
    in AuthProvider (created by Mutation)
    in Mutation
    in Unknown (created by Mutation)
    in Mutation
    in Unknown (created by AuthProviderOperations)
    in AuthProviderOperations (created by Routes)
    in Routes (created by App)
    in Query
    in Unknown (created by ShopProvider)
    in ShopProvider (created by App)
    in AppStateProvider (created by App)
    in MessageManager (created by App)
    in IntlProvider (created by LocaleProvider)
    in LocaleProvider (created by App)
    in DateProvider (created by App)
    in ThemeProvider (created by ThemeProvider)
    in ThemeProvider (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in ApolloProvider (created by App)
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js?61bb:21810
logError @ react-dom.development.js?61bb:21847
callback @ react-dom.development.js?61bb:23235
callCallback @ react-dom.development.js?61bb:13810
commitUpdateEffects @ react-dom.development.js?61bb:13848
commitUpdateQueue @ react-dom.development.js?61bb:13838
commitLifeCycles @ react-dom.development.js?61bb:22102
commitLayoutEffects @ react-dom.development.js?61bb:25302
callCallback @ react-dom.development.js?61bb:336
invokeGuardedCallbackDev @ react-dom.development.js?61bb:385
invokeGuardedCallback @ react-dom.development.js?61bb:440
commitRootImpl @ react-dom.development.js?61bb:25040
unstable_runWithPriority @ scheduler.development.js?3069:818
runWithPriority$2 @ react-dom.development.js?61bb:12130
commitRoot @ react-dom.development.js?61bb:24889
finishSyncRender @ react-dom.development.js?61bb:24296
performSyncWorkOnRoot @ react-dom.development.js?61bb:24274
eval @ react-dom.development.js?61bb:12180
unstable_runWithPriority @ scheduler.development.js?3069:818
runWithPriority$2 @ react-dom.development.js?61bb:12130
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:12175
flushSyncCallbackQueue @ react-dom.development.js?61bb:12163
discreteUpdates$1 @ react-dom.development.js?61bb:24390
discreteUpdates @ react-dom.development.js?61bb:1442
dispatchDiscreteEvent @ react-dom.development.js?61bb:5885

**Comment by karolkielecki** [comment]
@joelunmsm2003 Hi there! Could you please tell us all the steps you have taken? It will help us to reproduce your issue. We haven't found any problem so far...

Please also use our ticket template in the future:
### What I'm trying to achieve
…

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
…

Best

**Comment by lbrito55** [comment]
I’m having the same error @karolkielecki 

I’m trying to create a product in dashboard

Created a product and the state is not published
Click on publish
![B686E3CE-953C-407B-8C36-94BAC151E671](https://user-images.githubusercontent.com/26174143/72821597-17ed6580-3c47-11ea-9a39-9e3ab88c58b4.jpeg)
Error
![A591C79A-12B5-412C-B4D3-F5709E24F733](https://user-images.githubusercontent.com/26174143/72821598-1885fc00-3c47-11ea-9c4f-32fc3631ee35.jpeg)
This is the error
![22668085-4625-4837-BC3A-F38A6171426B](https://user-images.githubusercontent.com/26174143/72821445-e379a980-3c46-11ea-84af-1fc266790550.jpeg)

That product is being saved in the server but I’m unable to publish any products, even if I’m uploading two at the same time
Ie
![D23765BF-3AD2-4AE0-BE00-1DCF1623B60D](https://user-images.githubusercontent.com/26174143/72821767-60a51e80-3c47-11ea-89e3-cf5b500976f4.jpeg)
![13924954-CE02-4D9D-93AD-261F2C6944DC](https://user-images.githubusercontent.com/26174143/72821769-60a51e80-3c47-11ea-845a-f12415ee561b.jpeg)
![3F063F43-4D55-4794-9F37-7B63FE1C008B](https://user-images.githubusercontent.com/26174143/72821771-613db500-3c47-11ea-870c-a21f229ad644.jpeg)

**Comment by AlmogCohen** [comment]
As I understand there are two bugs reported here that I've just reported in another thread as the name here was not clear: 
1. buttons not working in the product view. #387 
2. Products not being published #388

**Comment by karolkielecki** [comment]
@lbrito55 @joelunmsm2003 Hey guys! Do you use the Saleor master branch or version 2.9?

**Comment by lbrito55** [comment]
@karolkielecki master branch

**Comment by maarcingebala** [comment]
Thanks for reporting, we'll try to fix all these issues as soon as we can.
