### ISSUE TITLE
Cannot Create New product 

### ISSUE THREAD

**Issue by Pichnyty** [mirumee/saleor-dashboard#384]
### What I'm trying to achieve
…
Able to create new product
### Steps to reproduce the problem
1. Sign in As usual
2. Navigate to product 
3. Fill all the form of creating product
4. Click on " Creat Product " Button

### What I expected to happen
…
Able to create the product
### Screenshots

Saleor ran into an unexpected problem
![Capture](https://user-images.githubusercontent.com/54165288/73269584-af3a5600-420f-11ea-920d-8e305aceb4cf.JPG)

**System information**
Operating system: Window 10
Browser: Chrome

**Comment by karolkielecki** [comment]
Hello @Pichnyty. Thanks for reporting the issue. We think there is a bug on the Saleor master branch. Do you use the master branch or version 2.9.1?

**Comment by Pichnyty** [comment]
Yes, I did clone the project from master branch based on the link document below.
https://saleor.readthedocs.io/en/stable/gettingstarted/installation-windows.html

I'd appreciate what is the latest version of saloer that i'm able to use

**Comment by karolkielecki** [comment]
For the latest stable version, we recommend using the following release tag
https://github.com/mirumee/saleor/releases/tag/2.9.1

**Comment by Pichnyty** [comment]
I want to be the contributor of this opensource but I have no knowledge with GraphQL. So could you tell me 
1. how can i be contributor 
2. What should I start to learn how to use Graphql
I've experienced with only Django and PSQL

**Comment by Pichnyty** [comment]
2nd Question : What version of "saleor", "saleor-storefront" that's able to work and synchronized with the "saleor-dashboard 2.9.1" ?

**Comment by karolkielecki** [comment]
Happy to hear that you would like to become a contributor! Saleor is a standard Django app. If you would like to learn Django then I recommend you to go through the docs: https://docs.djangoproject.com/en/3.0/ 

The latest stable version Saleor 2.9.1 version:
https://github.com/mirumee/saleor/releases/tag/2.9.1

Saleor Dashboard 2.0: 
https://github.com/mirumee/saleor-dashboard/releases
https://github.com/mirumee/saleor-dashboard#getting-started

Saleor Storefront: 
https://github.com/mirumee/saleor-storefront/releases/tag/v0.7.0
https://github.com/mirumee/saleor-storefront#getting-started

**Comment by Pichnyty** [comment]
Thank you for this information

**Comment by karolkielecki** [comment]
You're welcome. If you have any questions or feedback, you can also contact me on Gitter or Spectrum.
https://spectrum.chat/saleor
https://gitter.im/mirumee/saleor

**Comment by dominik-zeglen** [comment]
Hey, can you tell me what data did you put in the form?
I can't reproduce this, so it may be some corner case here.
Also, you speak of product creation, but posted some error caused by product list, which is not related, but will be fixed in a few minutes :)

**Comment by Pichnyty** [comment]
I did input the data in the form as usual but I can't create. it appear "Saleor run into problem" as the screen shot above

**Comment by Pichnyty** [comment]
Hi @dominik-zeglen @karolkielecki, I'm not sure whether it's a bug or what mistake from my side but I can't create the product in saleor-dashboard. I've tried to follow all the instruction in the document and the error is like below image
**_"saleor.warehouse.models.Warehouse.DoesNotExist: Warehouse matching query does not exist."_**
![XXX](https://user-images.githubusercontent.com/54165288/73611730-70453f80-4617-11ea-9856-d472e7da18ad.JPG)

However if i migrate sample data " python manage.py populatedb --createsuperuser" as in the doc I'm able to create the product. Could you tell me what is wrong from my side ?

![DXXX](https://user-images.githubusercontent.com/54165288/73611754-c914d800-4617-11ea-8bc4-725ef9687841.JPG)

Infor: Collection, Attribute, Product Type, Categories created already.
