### ISSUE TITLE
Don't store JSON Web token in local storage or session storage

### ISSUE THREAD

**Issue by saschametz** [mirumee/saleor-dashboard#385]
Currently Saleor is using the local storage or session storage to store the JSON Web token which is like a password that expires after a short amount of time.

According to Auth0 and several other resources the local storage or session storage should not be used to store sensitive data like the JWT. ([Auth0](https://auth0.com/docs/tokens/guides/store-tokens#don-t-store-tokens-in-local-storage), [OWASP](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/HTML5_Security_Cheat_Sheet.md#local-storage))

If Saleor plans to offer plugins from third parties this becomes even more important because this offers more potential for XSS attacks.

IMHO it would be the best solution to store the access token in a cookie with the *HttpOnly* and *Secure* flag ([Reference](https://youtu.be/WzfJgCOMIsU?t=1467)) but I understand the implementation doesn't work that easy since the dashboard is a SPA.

**Comment by maarcingebala** [comment]
Hey @saschametz, we'll be reworking this - please see this issue comment for details: https://github.com/mirumee/saleor/issues/5128#issuecomment-580693586
