### ISSUE TITLE
Errors while saving product are not handled correctly

### ISSUE THREAD

**Issue by AlmogCohen** [mirumee/saleor-dashboard#386]
### What I'm trying to achieve
Make a product visible while it has no category set and:
1. Have the error from the server properly shown to the user within the dashboard.
2. Revert the product changes ("Visible" back to "Hidden") as the save has failed.

### Steps to reproduce the problem
1. Clone the master branch (did this yesterday)
2. Go to admin -> Catalogue -> Products
3. Create new product, give it a name, *do not* give it any category.
4. Hit "save".
5. Now change the product to "Visible" and hit "Save".
6. The button indicates an error, but no error is indicated to the user.
7. It seems like the product was saved, while in practice it was not saved due to an error.
8. A non technological user would never know that the save failed, not why

### What I expected to happen
I expected the "Save" to fail, the error to be visible, and the "Visible" button to be changed back to "Hidden" since the object was not saved. I expected the error message to be communicated to me as the user in a meaningful way.

### Screenshots
A video demonstrating that: https://share.getcloudapp.com/NQuvXpvx

**System information**
Operating system: OSX Catalina
Browser: Lastest chrome

**Comment by maarcingebala** [comment]
Thanks for reporting, we'll try to look into this issue as soon as we can.

**Comment by AlmogCohen** [comment]
Thanks 👍 Just confirmed this is also present on 2.0 + 2.9
