### ISSUE TITLE
Product operations from the products list failing with exception

### ISSUE THREAD

**Issue by AlmogCohen** [mirumee/saleor-dashboard#387]
### What I'm trying to achieve
1. Select a product from the product list view.
2. Try to delete or publish the product.
3. Both "delete" and "publish" are failing with exceptions.

### Steps to reproduce the problem
1. Navigate to the product list view (http://localhost:9000/products/?asc=true&sort=name)
2. Select a product https://share.getcloudapp.com/ApuOdlDX
3. Click the "bin" icon on the top of the list https://share.getcloudapp.com/5zuJqb2d
4. BOOM! Unhandled error and the FE client crash https://share.getcloudapp.com/X6uD6nvB

It might be worth noting that if I click into the product page and hit "delete", it works perfectly
Edit: It seems that if I choose more than one product (aka 2) the product operations do work! What a magic :)

### What I expected to happen
The product to be deleted successfully

### Screenshots
See screenshots above

**System information**
Operating system: OSX Catalina
Browser: Latest chrome

**Comment by AlmogCohen** [comment]
Hi guys! I really like your project...the documentation and the brand website seem promising! I do find it a bit disappointing to find these basic functionality bugs (this one along the #386) after playing with the dashboard only for ~15 minutes. Nothing complicated or bizarre... Is it a common experience for the dashboard is so unstable?

Is there anything I might be doing wrong? Maybe I shouldn't be working with master head? Is there a stable release / branch I should be working with instead of the simple repo clone?

I also understand that the Dashboard 2.0 is pretty new and is in beta (not trying to point any fingers, but from my short experience it feels more like an alpha), would you recommend using another saleor version which came before the Dashboard 2.0 came out? 

I'd appreciate your advice very much! I'm looking forward to find a way to take full advantage of this amazing project

**Comment by AlmogCohen** [comment]
I was debugging and it seems like in [this line](https://github.com/AlmogCohen/saleor-dashboard/blob/8ddf66f1349f79fedef8be9275f0e312e76b098f/src/products/views/ProductList/ProductList.tsx#L78) `params.ids` is passed as "<some-product-id>" and not as a list of product ids as the code in `isSelected` is expecting.

**Comment by karolkielecki** [comment]
Hey! @AlmogCohen! It looks like a bug on the master branch. Please install Saleor 2.9.1 - it's the latest stable version. We're going to fix the issue, but I'm not sure when it will happen. If you have any questions or feedback, let us know.

**Comment by maarcingebala** [comment]
If you're using the version from `master`, it may be unstable with the current `master` branch of Saleor backend. We recommend using release versions:
- https://github.com/mirumee/saleor/releases/tag/2.9.1
- https://github.com/mirumee/saleor-dashboard/releases/tag/v2.0.0

We're working on improving our release cycle better - having smaller releases, but more often and making them more stable. 

We have the [legacy-views](https://github.com/mirumee/legacy-views) repo where we have the old version of Saleor with Django-based storefront and dashboard. It's not maintained anymore and has fewer features, but if you're more like Python/Django developer, then you might be interested in that as well.

**Comment by AlmogCohen** [comment]
I can now confirm that this bug is *NOT* present  on the 2.0 + 2.9 release
