### ISSUE TITLE
Project Start!

### ISSUE THREAD

**Issue by yonesb9** [mirumee/saleor-dashboard#397]
Hi
I want to run the project. This error is displayed and I do not know where the problem is and why this error occurred to me.
[http://s6.picofile.com/file/8387060150/saleor.png](url)
I did all this work and still have the same problem!
" npm i" "npm i -f" And " Remove node_modules folder and package-lock.json file and reinstall 'npm i' "
Help me please!
Thank you (^_^).

**Comment by maarcingebala** [comment]
It seems like webpack-dev-server wasn't installed correctly. There are some threads about this issue on the internet, please take a look for example here: https://stackoverflow.com/questions/35810172/webpack-is-not-recognized-as-a-internal-or-external-command-operable-program-or

**Comment by yonesb9** [comment]
> It seems like webpack-dev-server wasn't installed correctly. There are some threads about this issue on the internet, please take a look for example here: https://stackoverflow.com/questions/35810172/webpack-is-not-recognized-as-a-internal-or-external-command-operable-program-or

I have read and tested your guide but still have the same problem with the program and really do not know where to solve the problem! 

This problem is the same for both the " saleor-storefront " project and the " saleor-dashboard " project!

**Comment by maarcingebala** [comment]
There is some issue with the installation of your dependencies. `webpack-dev-server` should be present in `./node_modules/.bin/` catalog. Which version of Node and NPM are you using? Are there any errors when you run `npm i`?

**Comment by yonesb9** [comment]
There are 3 files for " webpack-dev-server " in the ( ./node_modules/.bin/ ) folder!
1- webpack-dev-server
2- webpack-dev-server.cmd
3- webpack-dev-server.ps1
My Npm Version: 6.13.6
My Node Version: 12.14.1
![screen-cmd](https://user-images.githubusercontent.com/20461826/73740077-b8ba4580-475c-11ea-875a-fa79241fa1f0.png)
![screen-file](https://user-images.githubusercontent.com/20461826/73740180-eef7c500-475c-11ea-9ad4-c6bc6cae9769.png)
When running the npm command i will show no error (^-^)

**Comment by yonesb9** [comment]
> There is some issue with the installation of your dependencies. `webpack-dev-server` should be present in `./node_modules/.bin/` catalog. Which version of Node and NPM are you using? Are there any errors when you run `npm i`?

There are 3 files for " webpack-dev-server " in the ( ./node_modules/.bin/ ) folder!
1- webpack-dev-server
2- webpack-dev-server.cmd
3- webpack-dev-server.ps1
My Npm Version: 6.13.6
My Node Version: 12.14.1
![screen-cmd](https://user-images.githubusercontent.com/20461826/73740077-b8ba4580-475c-11ea-875a-fa79241fa1f0.png)
![screen-file](https://user-images.githubusercontent.com/20461826/73740180-eef7c500-475c-11ea-9ad4-c6bc6cae9769.png)
When running the npm command i will show no error (^-^)

**Comment by maarcingebala** [comment]
Look at the error message - it says "Environment variable API_URI not set". `API_URI` is the address of the Saleor backend. If you're running the API with the default settings it should be available at `localhost:8000`. Please read a section about it in our readme: https://github.com/mirumee/saleor-dashboard/#configuration
If you're not familiar, please also read about setting environment variables on Windows.

**Comment by yonesb9** [comment]
i have just did what you saied but i didnt solve.
can you help me by the more details guidenence? such as video or screen shots?
I really thanks you for spending time to help me.

**Comment by yonesb9** [comment]
> Look at the error message - it says "Environment variable API_URI not set". `API_URI` is the address of the Saleor backend. If you're running the API with the default settings it should be available at `localhost:8000`. Please read a section about it in our readme: https://github.com/mirumee/saleor-dashboard/#configuration
> If you're not familiar, please also read about setting environment variables on Windows.

i have just did what you saied but i didnt solve.
can you help me by the more details guidenence? such as video or screen shots?
I really thanks you for spending time to help me.

**Comment by maarcingebala** [comment]
Unfortunately, we yet don't have any video tutorials about setting up Saleor. Did you set the `API_URI` variable? What happens now when you run `npm i` and `npm start`?

**Comment by yonesb9** [comment]
yes I did . i sent you the screen shot . will you help me if I give you the access of computer with anydesk?
![scrsh](https://user-images.githubusercontent.com/20461826/73822001-69cae980-480a-11ea-8fd5-2b7c3f673f89.png)

**Comment by yonesb9** [comment]
> Unfortunately, we yet don't have any video tutorials about setting up Saleor. Did you set the `API_URI` variable? What happens now when you run `npm i` and `npm start`?

yes I did . i sent you the screen shot . will you help me if I give you the access of computer with anydesk?
![scrsh](https://user-images.githubusercontent.com/20461826/73822001-69cae980-480a-11ea-8fd5-2b7c3f673f89.png)

**Comment by maarcingebala** [comment]
I see the prompt `Terminate batch job (Y/N)?` - you shouldn't terminate that process - it takes some time for webpack-dev-server to build and start serving all project files.
