### ISSUE TITLE
Description missing on dashboard

### ISSUE THREAD

**Issue by tboulogne** [mirumee/saleor-dashboard#402]
### What I'm trying to achieve
Description not appears on dashboard. (description is present into the record when checking graphql)

### Steps to reproduce the problem
1. Create or Update a product
2. Open the record on Dashboard

### Screenshots
**from graphql**
![image](https://user-images.githubusercontent.com/6205275/74329630-78784a00-4d90-11ea-8ad2-5b17f779cc3b.png)

**from dashboard**
![image](https://user-images.githubusercontent.com/6205275/74329717-9b0a6300-4d90-11ea-9e89-921bacb4a0db.png)

### system
> latest saleor
> latest saleor-dashboard

thanks for help

**Comment by dominik-zeglen** [comment]
This is because dashboard uses `descriptionJson` field instead of `description`.

**Comment by tboulogne** [comment]
@dominik-zeglen thanks

It's strange because docs said `descriptionJson` not recommended !!! :-(
![image](https://user-images.githubusercontent.com/6205275/74434995-cd38c500-4e63-11ea-9250-96367a4b68ca.png)

Something to solve somewhere :-) !!!

**Comment by maarcingebala** [comment]
This field description that you mentioned comes from Graphene which is interesting, as this is exactly the use case where we have to store data in JSON.

**Comment by tboulogne** [comment]
So, i could i send description when i create product with graphql and see description into dashboard please ?

**Comment by tboulogne** [comment]
for next guy with this problem, found this : https://pypi.org/project/html-to-draftjs/
