### ISSUE TITLE
ERR RUN GRAPHQL

### ISSUE THREAD

**Issue by yonesb9** [mirumee/saleor-dashboard#405]
Hi
When I run the project and want to get to the dashboard page, I get this error.
##
I know the problem is with graphql but I don't know how to run it!
##
Do I need to run a project to run graphql or do I have to install the program ?!
##
How do I fix the issue and access the dashboard ?!
Thank You Very Much 🙏
### Screenshots
![photo_2020-02-15_10-25-20](https://user-images.githubusercontent.com/20461826/74583721-50325a80-4fdf-11ea-87fc-2760f85b8fd7.jpg)

**System information**
Operating system: Windows 10
Browser:  Google Chrome

**Comment by yonesb9** [comment]
@dominik-zeglen @maarcingebala @benekex2 Help Me Please!

**Comment by karolkielecki** [comment]
@yonesb9 Hey! Are you running Saleor locally? If yes, then please set API_URI to: http://localhost:8000/graphql/

**Comment by gabernalt** [comment]
Hi, I'm having the same problem... I'm running Saleor locally and have ran "set API_URI="http://localhost:8000/graphql/" or should I set it in some specific file (app.json, config.base.js)? thanks

**Comment by maarcingebala** [comment]
@yonesb9 @gabernalt Please try to run Saleor using our [saleor-platform](https://github.com/mirumee/saleor-platform) project - it's using docker-compose to run all components at once. Make sure to assign at least 4 or even 6GB RAM to your Docker containers as building frontend apps requires more memory then Docker originally has configured.

**Comment by gabernalt** [comment]
Thanks @maarcingebala , I've installed Docker and started following the instructions on the saleor-platform project, however when I clone the repository using "git clone git@github.com:mirumee/saleor-platform.git --recursive --jobs 3" I get this error:

(Saleor2) C:\Users\Tavo\Dev\Saleor2\saleor>git clone git@github.com:mirumee/saleor-platform.git --recursive --jobs 3

Cloning into 'saleor-platform'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by gabernalt** [comment]
Thanks @maarcingebala , I've installed Docker and started cloning the saleor-platform repository but I'm getting this error:

(Saleor2) C:\Users\Tavo\Dev\Saleor2\saleor>git clone git@github.com:mirumee/saleor-platform.git --recursive --jobs 3
Cloning into 'saleor-platform'...
Enter passphrase for key '/c/Users/Tavo/.ssh/id_rsa':
remote: Enumerating objects: 91, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (65/65), done.            jects:  12% (11/91)
remote: Total 91 (delta 47), reused 50 (delta 26), pack-reused 0R
Receiving objects: 100% (91/91), 36.66 KiB | 544.00 KiB/s, done.
Resolving deltas: 100% (47/47), done.
Submodule 'saleor' (git@github.com:mirumee/saleor.git) registered for path 'saleor'
Submodule 'saleor-dashboard' (git@github.com:mirumee/saleor-dashboard.git) registered for path 'saleor-dashboard'
Submodule 'saleor-storefront' (git@github.com:mirumee/saleor-storefront.git) registered for path 'saleor-storefront'
Cloning into 'C:/Users/Tavo/Dev/Saleor2/saleor/saleor-platform/saleor'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mirumee/saleor.git' into submodule path 'C:/Users/Tavo/Dev/Saleor2/saleor/saleor-platform/saleor' failed
Failed to clone 'saleor'. Retry scheduled
Cloning into 'C:/Users/Tavo/Dev/Saleor2/saleor/saleor-platform/saleor-dashboard'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by dominik-zeglen** [comment]
> Hi, I'm having the same problem... I'm running Saleor locally and have ran "set API_URI="http://localhost:8000/graphql/" or should I set it in some specific file (app.json, config.base.js)? thanks

Set is as an environment variable.
