### ISSUE TITLE
Upgrade workflow for cleaning db in saleor-dashboard for all versions

### ISSUE THREAD

**Issue by karola312** [mirumee/saleor-dashboard#4096]
Right now we have a dedicated snapshot on lower version. With this snapshot, we restore all release environments (eg. https://vXX.staging.saleor.cloud). When we want to add some new data, we have to create a new snapshot and update the snapshot key in GitHub workflow. There is a problem with the new versions. If there is a new feature, only on the latest versions we have an issue with adding data there - because our snapshot is on a lower version.

Solution: 
1. In workflow send request to get all snapshot with name contains "snapshot-automation-tests" or something like that.
2. Check is there is snapshot for the environment we want to restore. (eg check if for env v311 there is snapshot with 3.11 version). If not get snapshot with highest version below current. (eg 3.10)
3. Restore db with this snapshot.

When we will want to add some new data:
1. Enter release environment
1. Restore form snapshot with highest version - equal or below current
2. Add new data
3. Save snapshot with name contains "snapshot-automation-tests"

**Comment by wojteknowacki** [comment]
4. Save snapshot with name contains "snapshot-automation-tests-`version`" like "snapshot-automation-tests-3.14"

**Comment by wojteknowacki** [comment]
Why do we need to `Restore form snapshot with highest version - equal or below current` before adding new data?

**Comment by wojteknowacki** [comment]
@karola312 👍 :)
