### ISSUE TITLE
Add Product on create Order not working

### ISSUE THREAD

**Issue by tilman** [mirumee/saleor-dashboard#41]
### What I'm trying to achieve
adding an Item to an Order

### Steps to reproduce the problem
1. Open All Orders
2. click Plus for new Order
3. click add Products
4. select Product
5. no button to save is visible (maybe the button is offscreen)

### What I expected to happen
an button to save

### Screenshots
![sal](https://user-images.githubusercontent.com/5111431/58367984-64c94280-7ee6-11e9-818d-70b7b341763f.jpeg)

**System information**
Operating system: Mac OSX
Browser: Chrome (latest)

**Comment by dominik-zeglen** [comment]
Fixed some time ago, not knowing exactly when 🤷‍♂️
