### ISSUE TITLE
404 Error when opening multiple dashboard tabs

### ISSUE THREAD

**Issue by petedermott** [mirumee/saleor-dashboard#416]
### What I'm trying to achieve
Open the dashboard in multiple tabs

### Steps to reproduce the problem
1. Install backend / dashboard as normal
2. Login to dashboard
3. Go to any page
4. Right click another link in the dashboard's left hand navigation panel and open it in a new tab

### What I expected to happen
You can view the dashboard in multiple tabs

### What actually happens
You are prompted to login again, upon successfully logging in you are then presented with a 404 error page

**System information**
Operating system: Windows 10 Pro
Browser: Firefox 73.0.1

**Comment by karolkielecki** [comment]
@petedermott Hey! Thanks for reporting. It looks like a bug. We'll investigate it as soon as we can.

**Comment by krzysztofwolski** [comment]
Cannot reproduce the issue.
