### ISSUE TITLE
Error when I click on shipping zones or create new shipping zone

### ISSUE THREAD

**Issue by JuanTwoThree** [mirumee/saleor-dashboard#417]
### What I'm trying to achieve
Create a shipping zone or edit one. 

### Steps to reproduce the problem
1. click on create shipping zone

### What I expected to happen
I expect to create a new shipping zone

### Screenshots
<img width="1153" alt="Screen Shot 2020-02-26 at 11 35 46 AM" src="https://user-images.githubusercontent.com/18391388/75376251-f9553c80-588c-11ea-91dc-432352ecfb00.png">

**System information**
Operating system: macOS Catalina
Browser: Chrome

**Comment by karolkielecki** [comment]
@JuanTwoThree Hey! Thanks for reporting. We'll check it out.
