### ISSUE TITLE
Store Information with shadow Required fields

### ISSUE THREAD

**Issue by Ulisses1478** [mirumee/saleor-dashboard#418]
### What I'm trying to achieve
Put data in Store Information without Country Area

### Steps to reproduce the problem
1. Fresh Install
2. Try to put some data but not on Country Area

### What I expected to happen
To work?

**System information**
Operating system: Linux

**Comment by maarcingebala** [comment]
What is exactly your use-case where you don't want to provide the country area? There is an address validation library underneath that checks if the provided address is complete; for some countries, the country area is optional while for some others it may be mandatory.

**Comment by Ulisses1478** [comment]
There is no need but, I think it is a visual bug on my instalation that when I don't put it it wont show it is a required field. But That's fine.
