### ISSUE TITLE
Costumer not opening

### ISSUE THREAD

**Issue by Ulisses1478** [mirumee/saleor-dashboard#419]
### What I'm trying to achieve
Trying to see costumer info

### Steps to reproduce the problem
1. Fresh install
2. Create a costumer and click on it

### What I expected to happen
Open edit costumer form with all the info

### Screenshots
![Captura de Tela 2020-03-02 às 19 12 29](https://user-images.githubusercontent.com/39404063/75722894-e346e200-5cb9-11ea-8aa3-9ec885e51266.png)

# localhost:9000/dashboard/customers/VXNlcjo0
![Captura de Tela 2020-03-02 às 19 13 00](https://user-images.githubusercontent.com/39404063/75722901-e772ff80-5cb9-11ea-8e2b-cee0c87fc525.png)

**System information**
Operating system: Ubuntu and Mac
Browser: Brave (Mac), Chrome (Mac) and Firefox (Ubuntu

**Comment by maarcingebala** [comment]
Thanks for reporting, I've checked locally and confirmed this error. We'll try to look into it as soon as we can.
