### ISSUE TITLE
A question not a bug not a request feature

### ISSUE THREAD

**Issue by Ulisses1478** [mirumee/saleor-dashboard#420]
### What I'm trying to achieve
Run NGINX as a reverse proxy to this application

### Steps to reproduce the problem
1. server ip 10.0.0.99:9000/dashboard/ works fine, no problem (just some bugs)
2. https://xxxx.duckdns.org/dashboard/ with SSL I get the error "Saleor ran into an unexpected problem" 

### Notes
http://xxxx.duckdns.org/dashboard/ (WITHOUT SSL) Works

### What I expected to happen
Get connection to graphql

### Screenshots
![Captura de Tela 2020-03-02 às 19 22 40](https://user-images.githubusercontent.com/39404063/75723498-34a3a100-5cbb-11ea-94b3-d4f4cd12c556.png)

**System information**
Operating system: Mac OS
Browser: Brave and Chrome

**Comment by karolkielecki** [comment]
@Ulisses1478 Hi there! Did you set up correctly the environment variables API_URI?

**Comment by dominik-zeglen** [comment]
Maybe you're accessing API using `http` and not `https`?

**Comment by Ulisses1478** [comment]
> @Ulisses1478 Hi there! Did you set up correctly the environment variables API_URI?

API_URI="http://10.0.0.99:8000/graphql" 

I should open api to public domain?

**Comment by dominik-zeglen** [comment]
I get a feeling that there should be a trailing slash. There's authentication via JWT in headers, so it's safe as it is.
