### ISSUE TITLE
[Orders] It shouldn't be possible to add an empty notes

### ISSUE THREAD

**Issue by michalina-graczyk** [mirumee/saleor-dashboard#423]
### Steps to reproduce the problem
1. Go to orders
2. Select some random order
3. Go to the order history
4. Add an empty note

### What I expected to happen
It shouldn't be possible to add an empty note.
### Screenshots
![image](https://user-images.githubusercontent.com/25908728/75779114-594e5600-5d59-11ea-8b86-ed1c4c166ea2.png)

**System information**
Operating system: MacOS
Browser: Google Chrome v.80

Priority: **Medium**

**Comment by dominik-zeglen** [comment]
Copying to core as well, backend should throw an error if message's length is zero.

**Comment by maarcingebala** [comment]
Backend throws a validation error now but some error should be also rendered in the frontend.

**Comment by krzysztofwolski** [comment]
Sending empty notes is no longer possible.
