### ISSUE TITLE
[Settings] Initials are not centred

### ISSUE THREAD

**Issue by michalina-graczyk** [mirumee/saleor-dashboard#424]
### What I'm trying to achieve
…

### Steps to reproduce the problem
1. Go to settings
2. Go to staff members
3. Look at the placeholder for a user image

### What I expected to happen
It Is expected to have initial letters to be centered.
### Screenshots

![image](https://user-images.githubusercontent.com/25908728/75786097-0f6b6d00-5d65-11ea-8137-a347e7fca034.png)

**System information**
Operating system: MacOS
Browser: Chrome v.80

**priority** Low

**Comment by krzysztofwolski** [comment]
Fixed in https://github.com/mirumee/saleor-dashboard/pull/639
