### ISSUE TITLE
Published column in product list doesn't show correctly if product `is_published`

### ISSUE THREAD

**Issue by kswiatek92** [mirumee/saleor-dashboard#426]
Published column in product list doesn't show correctly if product `is_published`
Product list in collection view display published correctly

### Screenshots
![image](https://user-images.githubusercontent.com/9078162/75786476-a9331a00-5d65-11ea-8f5e-d6c2fdccc668.png)

![image](https://user-images.githubusercontent.com/9078162/75786697-f7e0b400-5d65-11ea-8c65-b507682db4b5.png)

### What I expected
To see the same status for `AliceBlue 2` in both listings.

**Comment by maarcingebala** [comment]
Product type exposes two fields:
- `isPublished`
- `isAvailable`
It seems that the main product listing uses `isAvailable` for a column which should use `isPublished`.
