### ISSUE TITLE
shipping information needed

### ISSUE THREAD

**Issue by appleyuchi** [mirumee/saleor-dashboard#435]
### What I'm trying to achieve
…
Thanks for your huge work~
Does shipping information can be displayed in dashboard such as
![物流系信息](https://user-images.githubusercontent.com/27613483/76384008-a30df080-6398-11ea-9fad-d8b37c741994.png)
the picture is from:
https://t.17track.net/zh-cn#nums=CS459142747DE

Although I know **many famous ecommerce platform such  as Amazon,
they never show shipping information.**

but **Chinese Shipping system is very Fast and huge,
Chinese ecommerce platfrom always contain shipping information.
when the epidemic comes,customers are anxious to know where their goods are.
could you consider adding this feature?**

shipping  API  always needs to paid,then `api key/api secret` need to be input in saleor-dashboard.

### Describe a proposed solution
...
need api import and interface for engineers to input their own `api key/api secret`
I want information both be displayed in saleor-storefront(in customer's order) and in saleor-dashboard

### Other solutions I've tried and won't work
…

### Screenshots or mockups

![物流没有显示](https://user-images.githubusercontent.com/27613483/76383947-75c14280-6398-11ea-81bd-8ae22eaf471d.png)

**Comment by karolkielecki** [comment]
@appleyuchi Hey! Thank you for your suggestion. I'll pass your idea to the dev team, and we'll discuss it. Thanks!
