### ISSUE TITLE
Could not list products catalog

### ISSUE THREAD

**Issue by tboulogne** [mirumee/saleor-dashboard#442]
Hello,

A face this error when i try to access to catalog after updating on latest commit.

### What I'm trying to achieve
Access to Calalog list

### Screenshots
````
 "errors": [{
        "message": "'WSGIRequest' object has no attribute 'service_account'",
        "locations": [{
            "line": 28,
            "column": 3
        }],
        "path": ["products"],
        "extensions": {
            "exception": {
                "code": "AttributeError",
                "stacktrace": ["Traceback (most recent call last):", "  File \"/home/manager/.virtualenvs/saleor/lib/python3.8/site-packages/promise/promise.py\", line 489, in _resolve_from_executor", "    executor(resolve, reject)", "  File \"/home/manager/.virtualenvs/saleor/lib/python3.8/site-packages/promise/promise.py\", line 756, in executor", "    return resolve(f(*args, **kwargs))", "  File \"/home/manager/.virtualenvs/saleor/lib/python3.8/site-packages/graphql/execution/middleware.py\", line 75, in make_it_promise", "    return next(*args, **kwargs)", "  File \"/home/manager/saleor/saleor/graphql/core/fields.py\", line 176, in connection_resolver", "    iterable = resolver(root, info, **args)", "  File \"/home/manager/saleor/saleor/graphql/product/schema.py\", line 276, in resolve_products", "    return resolve_products(info, **kwargs)", "  File \"/home/manager/saleor/saleor/graphql/product/resolvers.py\", line 148, in resolve_products", "    user = get_user_or_service_account_from_context(info.context)", "  File \"/home/manager/saleor/saleor/graphql/utils.py\", line 191, in get_user_or_service_account_from_context", "    return context.service_account or context.user", "AttributeError: 'WSGIRequest' object has no attribute 'service_account'"]
            }
        }
    }],
```


Thanks for help on this.

**Comment by maarcingebala** [comment]
Hey, it seems like a backend related issue. [This middleware](https://github.com/mirumee/saleor/blob/3ca16900c2fc9fcb90ebca5970c351c088016ecd/saleor/graphql/middleware.py#L44) tries to get a service account from the request. We recently bumped Django and changed these middlewares slightly, did you upgrade your backend as well? Make sure that you installed new Python requirements and restarted the server. If that doesn't help I would also try removing all `*.pyc` files and restarting the server again.

**Comment by tboulogne** [comment]
thanks @maarcingebala for answer :

upgrade backend > done
python requirements > done
cleaning pyc > done

and same error... with same trace.

**Comment by maarcingebala** [comment]
@tboulogne Do you have any custom `settings.py` file with some overrides? Maybe `local_settings.py`?

**Comment by tboulogne** [comment]
yes, and nothing extravagant in it : 
```
from saleor.settings import *

# here you can override any Django settings e.g.:
VERSATILEIMAGEFIELD_SETTINGS = {
        'jpeg_resize_quality': 95,
        "create_images_on_demand": get_bool_from_env("CREATE_IMAGES_ON_DEMAND", DEBUG)

        }

ACCOUNT_EMAIL_VERIFICATION = "optional"
TIME_ZONE = "Europe/Paris"
```

**Comment by tboulogne** [comment]
@maarcingebala UPDATE:

For information could not access staff members page or service account page.

get the 404 oups....

**Comment by maarcingebala** [comment]
There is indeed an [issue with displaying the service account details page](https://github.com/mirumee/saleor-dashboard/issues/439). But other pages that you mentioned work for me, I'm on master in both projects. Really have no idea what could go wrong there 😕. Any errors in the browser's console (others than the original one)?

**Comment by tboulogne** [comment]
@maarcingebala removing build directory before rebuild help to solve this :-).
