### ISSUE TITLE
Creating dummy order - Stock matching query does not exist

### ISSUE THREAD

**Issue by keyboSlice** [mirumee/saleor-dashboard#455]
I am just in the process of getting saleor set up, I've just completed the SendGrid integration and I wanted to create a dummy order to test the email sending. (side question, is there a way to send a test email through Saleor without having to create an order?) 

When I try to add a product to the order in the dashboard, I receive an error as follows: 

```
{"errors": [{
     "message": "Stock matching query does not exist.", 
     "locations": [{"line": 170, "column": 3}],
     "path": ["draftOrderLinesCreate"], 
     "extensions": { ... redactedforclarity }
}]}
```

I'm guessing this is a compatibility mis-match between the dashboard and the api?  Will switching to the master branch of dashboard fix the issue (I checked out v2.0.0)

**Comment by maarcingebala** [comment]
We recommend using Dashboard 2.0.0 with the 2.9.1 version of the API. `master` of Saleor is currently unstable with `master` of the dashboard app. We're planning to fix it this or next week and release a new stable version in about two weeks.

**Comment by maarcingebala** [comment]
To answer your side question - the easiest way to test email sending is to request a password reset email through the storefront app.

**Comment by maarcingebala** [comment]
I'm adding the `bug` label, we'll verify this again after merging warehouses UI.

**Comment by keyboSlice** [comment]
Hi there, just to note that since updating dashboard and API to 2.10 I'm having no issues. Sorry for not updating this sooner.

After updating in the dashboard all of my product variants were showing a checked checkbox for 'track inventory', I think this might have been related to the issue I was experiencing as tracking inventory would require a warehouse configuration from which to deduct stock when orders complete? 

But yeah, all good as of latest update! Thanks again for everything you're doing
