### ISSUE TITLE
huge npm vulnerabilities count

### ISSUE THREAD

**Issue by tboulogne** [mirumee/saleor-dashboard#457]
### What I'm trying to achieve
Building dashboard after pulling last commit.

 ### What I expected to happen
low number of vulnerabilities

### Screenshots

![image](https://user-images.githubusercontent.com/6205275/77513520-7a482980-6e75-11ea-8458-072555c7b97c.png)

Anyone show this and solve it ?

Thanks for help.

Regards,

**Comment by dominik-zeglen** [comment]
We are aware of still having ~600 vulnerabilities after merging #459, but we decided that these come from one package used in developer tooling, so we'll wait for the fixes in packages that we use explicitly, not by remote.

**Comment by tboulogne** [comment]
ok
