### ISSUE TITLE
Warehouse matching query does not exist.

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor-dashboard#461]
### What I'm trying to achieve
Create a new product with stock > 0

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
I expect the product to be created successfully.

### Screenshots
Error Message:
```
errors: [{message: "Warehouse matching query does not exist.", locations: [{line: 207, column: 3}],…}]
0: {message: "Warehouse matching query does not exist.", locations: [{line: 207, column: 3}],…}
message: "Warehouse matching query does not exist."
locations: [{line: 207, column: 3}]
path: ["productVariantUpdate"]
extensions: {exception: {code: "DoesNotExist", stacktrace: ["Traceback (most recent call last):",…]}}
``` 
**System information**
Operating system: 
Browser:

**Comment by karolkielecki** [comment]
Hi @JannikZed We have recently added an unfinished implementation of warehouses to the Saleor master branch and UI doesn’t support it yet. Please, also bear in mind that the master branch is still unstable.

**Comment by maarcingebala** [comment]
This is a known problem and it will be fixed soon. There is the issue https://github.com/mirumee/saleor/issues/5180 to track it.
