### ISSUE TITLE
ERROR: This variant already exists

### ISSUE THREAD

**Issue by sebasgoldberg** [mirumee/saleor-dashboard#466]
### What I'm trying to achieve
I'm trying to modify a variant's stock.

### Steps to reproduce the problem
1. Create an attribute as dropdown (value required) and at least assign one attribute value.
2. Create a product type, set "Product type uses Variant Attributes", and assign the attribute already created in the previous step.
3. Create a category.
4. Create a product. Set the category and the product type already created in previous steps. Save the product. Once saved add variants to the product and save this variants.
5. Try to modify the stock for one of this variants and save, you will get the erro "This variant already exists".

### What I expected to happen
I expected that the variant will be saved.

### Screenshots
![image](https://user-images.githubusercontent.com/1379852/78314208-a6c40b80-752f-11ea-833f-5c5730114e40.png)

**System information**
Operating system: Ubuntu Server 18.04
Browser: Chrome
Saleor Version: v2.0.0

Thanks in advance!

**Comment by karolkielecki** [comment]
Hey @sebasgoldberg. Thanks for reporting. We are aware of this issue and we're working on it. If you find any errors or you have any questions, feel free to let us know.

**Comment by sebasgoldberg** [comment]
I am closing this issue because is the same that was reported in the saleor repo:

https://github.com/mirumee/saleor/issues/4933

Thank you
