### ISSUE TITLE
Password validation errors are not shown

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-dashboard#468]
### What I'm trying to achieve
To set password as a new staff user.

### Steps to reproduce the problem
1. Create a new staff user through the dashboard.
2. Receive an email with the link to set up password and click it.
3. Provide a password that doesn't validate against password rules, e.g. too short.

### What I expected to happen
To see a validation error.

### Screenshots

![image](https://user-images.githubusercontent.com/5421321/78534243-62b05f80-77ea-11ea-9a96-e7c2a476eb84.png)

**Comment by maarcingebala** [comment]
Errors in the `token` field are also not rendered:

```
{"data": {"setPassword": {"errors": [{"code": "INVALID", "field": "token", "__typename": "AccountError"}], "token": null, "user": null, "__typename": "SetPassword"}}}
```

**Comment by gabmartinez** [comment]
Hi @maarcingebala, I sent a PR to display the validation errors for the password field. I see now it must include the token field too. I can try to display that error.

Regards,
