### ISSUE TITLE
Update field name in graphql schema

### ISSUE THREAD

**Issue by d-wysocki** [mirumee/saleor-dashboard#472]
### What I'm trying to achieve
In this pull request [5469](https://github.com/mirumee/saleor/pull/5469/files/8741937f23223a5429f4792a4ce15f24c7b1edbb#diff-57f716f793ee52851859005993a036b1R3113) there is a chnage in `PluginUpdate` type, field `extensionsErrors` is changed into `pluginsErrors`, which is contain list of `PluginsError`. Dashboard also should be updated.

**Comment by maarcingebala** [comment]
Is this already resolved @dominik-zeglen @krzysztofwolski? Not sure if it should be closed.
