### ISSUE TITLE
Button "return to draft orders" moving to orders view

### ISSUE THREAD

**Issue by fowczarek** [mirumee/saleor-dashboard#481]
### What I'm trying to achieve
Back to draft order view. 

### Steps to reproduce the problem
1. Go to draft orders view 
2. Click on any draft order 
3. Click to "<- DRAFT ORDERS" button
4. I'm moved to orders view instead of draft orders view. 

The same bug appears when clicking back from create draft order view. 

### Screenshots
![image](https://user-images.githubusercontent.com/43955230/79450171-dae60480-7fe4-11ea-9252-74cf2e3d1f4f.png)

**System information**
Browser: Chrome

**Comment by krzysztofwolski** [comment]
Solved
