### ISSUE TITLE
Unable to Login into DashBoard as SuperUser

### ISSUE THREAD

**Issue by giovannipiccinelli** [mirumee/saleor-dashboard#484]
### What I'm trying to achieve
I am trying to log back into the admin dashboard. I have a live store running at www.storitalia.com

### Steps to reproduce the problem
1. Navigate to https://marketplace.storitalia.com/
2. Input login and password credentials. Credentials have been double checked multiple times, they are correct.

### What I expected to happen
I expect to login as for normal, but instead the following error message pops up "'extensions.manage_plugins' is not a valid PermissionEnum"

### Screenshots

![Schermata 2020-04-18 alle 11 35 50](https://user-images.githubusercontent.com/7911077/79634142-f8dc7200-8168-11ea-836f-1240220bde45.png)

**System information**
Operating system: MacOS
Browser: Chrome

**Comment by maarcingebala** [comment]
Hey, it's a known issue and we'll fix in the core repo next week. It's not related to the dashboard but to the core (API). You can solve it using Django's shell.
- make sure to pull the latest `master` of Saleor core repo
- run migrations: `python manage.py migrate`
- open the Django shell `python manage.py shell` and do the following:

```
from django.contrib.auth.models import Permission
p = Permission.objects.get(codename="manage_plugins", content_type__app_label="extensions")
p.delete()
```

This should fix the issue locally.

**Comment by giovannipiccinelli** [comment]
ok, that fixed the issue. Pls update the repo as mentioned 👍

**Comment by KarthikHebbarMN** [comment]
Hey, 
Facing the exact same issue when running on a GCP VM (debain os) using docker. 
The same perfectly works locally on Docker Desktop on WSL2. 
Tried this command twice with two different emails and passwords. The password and email then entered on the dashboard is correct, verified twice. 
`docker compose run --rm api python3 manage.py createsuperuser`

Looking forward to hear back from you
Thanks
