### ISSUE TITLE
SKU not configurable

### ISSUE THREAD

**Issue by Elrocho** [mirumee/saleor-dashboard#488]
### What I'm trying to achieve
I'm trying to add stock to my product

### Steps to reproduce the problem
1. I added the title, description, etc and clicked on pusblish (dashboard)
2. When trying to add the product to the cart, the option isn't available
3. When checking the product, the Inventory section must be 0 due to the SKU number, which isn't available to change

### What I expected to happen
1. Just being able to add products to the cart and have them in my inventory

### Screenshots

**System information**
Operating system: Win 10 pro 
Browser: Chrome

**Comment by dominik-zeglen** [comment]
Don't worry, we're on it: #390

**Comment by krzysztofwolski** [comment]
Fix merged
