### ISSUE TITLE
Unable to create/update a new product 

### ISSUE THREAD

**Issue by giovannipiccinelli** [mirumee/saleor-dashboard#501]
### What I'm trying to achieve

Hello I have a live shop running at www.storitalia.com and I have pulled all the available updates so far into my fork.

I have the following error message popping up when I either create or update a product: "Argument "input" has invalid value {attributes: $attributes, publicationDate: $publicationDate, category: $category, chargeTaxes: $chargeTaxes, collections: $collections, descriptionJson: $descriptionJson, isPublished: $isPublished, name: $name, basePrice: $basePrice, productType: $productType, sku: $sku, quantity: $stockQuantity, seo: $seo}.↵In field "quantity": Unknown field.""

### Steps to reproduce the problem
1. Login into the backend.
2. head toward new product 
3. select the product category and type, give a name to the product and establish a price.
4. hit save

### What I expected to happen
The product to be succssefully created.

### Screenshots
![Schermata 2020-04-27 alle 22 59 32](https://user-images.githubusercontent.com/7911077/80421159-5052ae80-88dc-11ea-802c-3e5104986163.png)

**System information**
Operating system: Mac OS
Browser: Chrome

**Comment by maarcingebala** [comment]
I'm not sure but this should be fixed by multi-warehouses PR: #390, is that right @dominik-zeglen?

**Comment by giovannipiccinelli** [comment]
This issue is resolved with the latest pull. Thanks 👍
