### ISSUE TITLE
After removing group which gives me manage staff I get error page

### ISSUE THREAD

**Issue by IKarbowiak** [mirumee/saleor-dashboard#503]
### What I'm trying to achieve
After removing the group which gives me permission to specific sites, I shouldn't get an error page.

### Steps to reproduce the problem
Perform these steps on the database after populatedb
1. Log in as admin (superuser)
2. Create a group with manage staff (let's name it `Test group`) and add some of the users to this group (not superuser)
3. Log out
4. Log in as a user from a group with manage staff
5. Remove `Test group`
6. You will get an error page

### What I expected to happen
I should be redirected to some page that I have access to, e. g. home page.

### Screenshots

![image](https://user-images.githubusercontent.com/40886528/80463318-537b8800-8938-11ea-8048-c7f518e31309.png)

**Comment by krzysztofwolski** [comment]
Thats not a bug. Thats the feature!

When trying accessing page you do not have access, you should be presented with 404 error instead of permission denied.

**Comment by IKarbowiak** [comment]
I can't agree with you. I should be redirected to another page that I have access to, after removing the group. I don't want to see the error page after removing the group.
