### ISSUE TITLE
After saving data on permission group site, save button should be deactivated

### ISSUE THREAD

**Issue by IKarbowiak** [mirumee/saleor-dashboard#506]
### What I'm trying to achieve
Prevent double saving the same data.

### Steps to reproduce the problem
1. Log in as admin
2. Go to permission group page (save button is deactivated)
3. Change something, e.g. name (save button is active)
4. Save data

### What I expected to happen
After save, the save button should be deactivated until the data change again.

### Screenshots

![image](https://user-images.githubusercontent.com/40886528/80469042-4e223b80-8940-11ea-8e40-ae0115845f63.png)

**Comment by krzysztofwolski** [comment]
Notes for later investigation: found similiar behaviour in few other places of dashboard.

**Comment by krzysztofwolski** [comment]
Issue no longer exists
