### ISSUE TITLE
Discount is not rendered on the order details view

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-dashboard#512]
### Steps to reproduce the problem
1. Place an order using storefront/checkout API and use a discount code for products.

### What I expected to happen
To see the discount included on the order details page

### Screenshots
There should be a discount -$18 rendered in the summary:
![image](https://user-images.githubusercontent.com/5421321/80944335-9aaac280-8de9-11ea-840d-7e8afb9da659.png)

Discount data returned from API for this order:
```json
{
  "data": {
    "order": {
      "total": {
        "gross": {
          "amount": 3.69
        }
      },
      "discount": {
        "amount": 18
      },
      "discountName": "Big order discount"
    }
  }
}
```

**Comment by mirekm** [comment]
Shouldn't that one be fixed for the 2.10 RC2 and eventually final?
