### ISSUE TITLE
TypeError: user.logout is not a function

### ISSUE THREAD

**Issue by Akbarkz** [mirumee/saleor-dashboard#524]
### What I'm trying to achieve
Notify with message "Saleor ran into an unexpected problem" when graphql core api is not running or Graphql API is incorrect

### Steps to reproduce the problem
1.  Shutdown Saleor Core
2. Launch Dashboard 

### What I expected to happen
Notify with message "Saleor ran into an unexpected problem" 

### Screenshots
<img width="1241" alt="Screen Shot 2020-05-10 at 1 56 37 PM" src="https://user-images.githubusercontent.com/13500078/81493902-33e44800-92c6-11ea-8492-e1cb7f9bbde9.png">
<img width="647" alt="Screen Shot 2020-05-10 at 1 56 49 PM" src="https://user-images.githubusercontent.com/13500078/81493905-3c3c8300-92c6-11ea-867b-91d37d2a2f61.png">

### Root Cause

Line number 86 in queries.tsx  uses Array.every() on graphql errors array. Array.every() returns true even if array on which every() method is called is empty. 
![code](https://user-images.githubusercontent.com/13500078/81493958-99383900-92c6-11ea-9d07-8bdf283594af.png)

Same issue with mutations.tsx line number 50

**System information**
Operating system:MacOs Mojave
Browser: Chrome

**Comment by dominik-zeglen** [comment]
Cool, thanks for finding the cause, nice work with debugging :)
