### ISSUE TITLE
no propper error message

### ISSUE THREAD

**Issue by a-atalla** [mirumee/saleor-dashboard#527]
### What I'm trying to achieve
create a new category in the catalog

### Steps to reproduce the problem
1. Catalog > Categories > Create Category
2. Type in Category name an Arabic name   for example `زيوت`
3. Click  the save button

### What happens
1. the save button converts to Error
2. the response says that the `slug` field is required

### What I expected to happen
1. in case of error, a user-friendly error message should show the UI 

### Screenshots
<img width="1880" alt="Screen Shot 2020-05-14 at 4 28 54 AM" src="https://user-images.githubusercontent.com/536140/81886539-3d5b0200-959d-11ea-9663-5fe80e93cc84.png">

**System information**
Saleor Version: 2.10.0-rc.2
Operating system: macOS Catalina 10.15.4
Browser: Firefox

**Comment by maarcingebala** [comment]
This is the same as https://github.com/mirumee/saleor/issues/5640 and it's now fixed on master.
