### ISSUE TITLE
Missing field companyName in WarehouseAddressInput

### ISSUE THREAD

**Issue by dsarmiento84** [mirumee/saleor-dashboard#532]
### What I'm trying to achieve
Field companyName is missing in type WarehouseAddressInput. It is found in WarehouseCreateInput and WarehouseUpdateInput. This makes this field non-updateable in their respective mutation.

Also it is missing in WarehouseAddressInput type of the backend (it is found in WarehouseInput).

### Steps to reproduce the problem
1. Create or update a warehouse, filling a value in companyName field.
2. Check that it changed in database.

### What I expected to happen
WarehouseCreate or WarehouseUpdate mutation should update this field.

**Comment by maarcingebala** [comment]
Hey, I'm not sure I understand the issue. As you wrote, the `companyName` field is available in mutations to create/update a warehouse and it works. Why would you expect it also in `WarehouseAddressInput`?
