### ISSUE TITLE
Available shipping methods not updated when creating draft order

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor-dashboard#533]
### What I'm trying to achieve
I'm trying to create a draft order.

### Steps to reproduce the problem
1. Begin creating a draft order
2. Fill in the details (addresses, variants, etc)

### What I expected to happen
The available shipping methods should be dynamically updated as the draft is filled. Instead, I have to refresh the page to see available shipping methods.

**System information**
Operating system: Windows 10 x64
Browser: Firefox 76

**Comment by maarcingebala** [comment]
I would consider this as a UX/UI bug. Our dashboard should be dynamic where possible and this is a perfect example where it should be reloaded dynamically.
