### ISSUE TITLE
Product saved searches creates product saved searches AND attribute saved searches

### ISSUE THREAD

**Issue by cyberdemic** [mirumee/saleor-dashboard#537]
### What I'm trying to achieve
I'm trying to create a saved search under the Products section and NOT have it create the same search under the Configuration -> Attributes section.

### Steps to reproduce the problem
1. Go to Catalog -> Products
2. Create a saved search under the Products section

### What I expected to happen
I want to create a saved search for Products and have separate saved searches for the attributes section.

**Comment by maarcingebala** [comment]
It's a bug, it seems like components are reused in both views, which is fine, but the logic that checks in which view a filter was saved is buggy. Thanks for reporting!

**Comment by maarcingebala** [comment]
A few screenshots to show the bug. First I created the "Beers" filter in the product list:
![image](https://user-images.githubusercontent.com/5421321/82808009-5317d380-9e89-11ea-9b5e-fcbd4eadc86b.png)

It appears also in the Attributes table:
![image](https://user-images.githubusercontent.com/5421321/82808048-662aa380-9e89-11ea-9dce-1de5aac5f9a2.png)

**Comment by maarcingebala** [comment]
Also when you save the filter in the Attributes view, it will appear in the Products table.

**Comment by maarcingebala** [comment]
Related bug - when enabling some filters in the product list view, the "Save search" button doesn't appear. It only appears when typing something in the "search" input. At the same time I can save filtering in other list views, e.g. attributes list.

**Comment by Akbarkz** [comment]
This happens because both ProductList and AttributeList uses same key
```javascript

export const PRODUCT_FILTERS_KEY = "productFilters";

```
I think for attributes it should be renamed to something like
``` javascript

export const ATTRIBUTE_FILTERS_KEY = "attributeFilters";

```
