### ISSUE TITLE
Remove all text from products description

### ISSUE THREAD

**Issue by cyberdemic** [mirumee/saleor-dashboard#540]
### What I'm trying to achieve
I added a description to a product and would like to remove the text for now, but it doesn't seem to save when deleting all the text.

Deleting text from the description works if you don't delete all of it. But once you delete all of it, it doesn't get saved correctly. When refreshing the product the text is back.

### Steps to reproduce the problem
1. Create a product with a description and save it.
2. Remove all text from the description(so there is no description) and save it.

### What I expected to happen
I expect all the text to get deleted.

### Screenshots
![description-bug](https://user-images.githubusercontent.com/54118049/82857826-f4714a80-9ec6-11ea-8424-fdc012af82bb.png)

**System information**
Operating system: Windows / Docker
Browser: Chrome

**Comment by maarcingebala** [comment]
Thanks for reporting, it's a bug.

**Comment by krzysztofwolski** [comment]
Issue resolved in new description editor.
