### ISSUE TITLE
Filter Doesn't get cleared

### ISSUE THREAD

**Issue by Akbarkz** [mirumee/saleor-dashboard#541]
I'm not sure if this us bug or expected behavior

### What I'm trying to achieve
Clear table filters on click of clear button.

### Steps to reproduce the problem
1.  Open filter in any table
2.  Add some filter by clicking some checkboxes
3.  Click Done.
4. Clicking clear doesn't clear the filters

### What I expected to happen

One click of clear button the filters should be cleared

### Screenshots
![filter bug (1)](https://user-images.githubusercontent.com/13500078/82926732-72a21f80-9fa1-11ea-82e8-1a35217360b4.gif)

### RC
The reset function in useFilter is dispatching payload with current state of filter. 

![reset-filter](https://user-images.githubusercontent.com/13500078/82927431-8732e780-9fa2-11ea-83d0-6da1d72a3ca3.png)

Which can be changed to something like below to solve the issue.  Not sure if its correct way because filters are nested.

```javascript
const reset = () =>
    dispatchFilterAction({
      payload: {
        new: initialFilter.map(filter =>  {
          return {...filter, active:false}
        })
      },
      type: "reset"
    });

```

**Comment by maarcingebala** [comment]
Thanks for opening the issue. The idea was the the "Clear" button clears the temporary state of checkboxes before applying the filters, but I also find this a bit confusing. I think we should change it to just clear whatever is selected and reset the state at all.
