### ISSUE TITLE
Search by Tracking Number and send it to customer

### ISSUE THREAD

**Issue by wael-mohamed** [mirumee/saleor-dashboard#546]
### What I'm trying to achieve
Search by Tracking Number, edit it and send it by email to customer

**Comment by krzysztofwolski** [comment]
@maarcingebala @pwgryglak Search orders by tracking no seem to be a useful feature. WDYT?

**Comment by maarcingebala** [comment]
I guess search should be flexible as possible so I think it could be useful and it doesn't cost us much since we store tracking code in our DB. Not sure how would that work with shipping integrations but I think we will store it anyway.

**Comment by pwgryglak** [comment]
It seems like a good idea. Depends how we can handle it cost-wise. Other thing is: Will it be easy to handle orders with multiple fulfillments?

**Comment by krzysztofwolski** [comment]
AFAIK backend search should handle multiple fulfillmens in search.
