### ISSUE TITLE
Shipping Rate update is not working (with solution)

### ISSUE THREAD

**Issue by Dom4n** [mirumee/saleor-dashboard#552]
### What I'm trying to achieve
Update shipping rates.

Checked with saleor-platform right now with sample database - same results.

### Steps to reproduce the problem
1. Go to dashboard -> shipping zone -> shipping method
2. Try to edit existing Price Based Rates or Weight Based Rates by setting new value range
3. Save -> no errors - but rates are not updated

Price update is working.

### What I expected to happen
Should update rates.

### Screenshots
![obraz](https://user-images.githubusercontent.com/10115274/83925411-624f2900-a787-11ea-9c1b-0048e23e340c.png)
![obraz](https://user-images.githubusercontent.com/10115274/83925436-7135db80-a787-11ea-90d8-9685a8e2110d.png)

**System information**
Operating system: Linux
Browser: Chromium, FF

SOLUTION:

add `type` to input

```
shippingPriceUpdate (id: "U2hpcHBpbmdNZXRob2Q6Mg=="
  input: {
    price: "12"
    name: "UPSS"
    minimumOrderPrice: "10"
    maximumOrderPrice: "20"
    type: PRICE   <<<<<<<<<<<
  }) 
```

![obraz](https://user-images.githubusercontent.com/10115274/83927115-34201800-a78c-11ea-9921-756865ce9016.png)

why?
https://github.com/mirumee/saleor/blob/master/saleor/graphql/shipping/mutations.py#L179

and yes, it should be required field.

I would post just PR but I`m not a frontend guy and have no idea how to change this.

**Comment by maarcingebala** [comment]
Thanks for reporting, just checked it's indeed a bug.
