### ISSUE TITLE
Adding variant attributes to an existing product type

### ISSUE THREAD

**Issue by almousa1990** [mirumee/saleor-dashboard#608]
### What I'm trying to achieve
Adding variant attributes to an existing product type

### Steps to reproduce the problem
1. using the sample data, add a variant attribute to a product type (i.e. Color to "Top (clothing) type")
2. The variant attribute is added (without values) to all existing products assigned with this product type

### What I expected to happen
New variant attribute should not be available on existing products.

### Screenshots

![image](https://user-images.githubusercontent.com/4084573/87337397-0927a180-c54c-11ea-8944-8399ad2b5b87.png)

**System information**
Operating system: 
Browser:

**Comment by krzysztofwolski** [comment]
By design, editing existing product type will modify all products using such type. If you do not wish to modify existing products, you have to create new product type.

**Comment by robertology** [comment]
Yes, that seems like expected behavior to me. Though, showing an attribute with no options to select does not.
