### ISSUE TITLE
Index page broken: Cannot read property 'email' of null

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor-dashboard#615]
### What I'm trying to achieve
Loading the dashboard, version 2.10.1 with an existing Saleor Instance, version 2.10.1 as well.

```
TypeError: Cannot read property 'email' of null
    at eQ (dashboard.87a613336d3da350da15.js?51e5438dd30d46f8ce40:164)
    at dashboard.87a613336d3da350da15.js?51e5438dd30d46f8ce40:164
    at Array.map (<anonymous>)
    at Od (dashboard.87a613336d3da350da15.js?51e5438dd30d46f8ce40:164)
    at HomeActivityCard (dashboard.87a613336d3da350da15.js?51e5438dd30d46f8ce40:164)
    at p_ (dashboard.87a613336d3da350da15.js?51e5438dd30d46f8ce40:126)
    at X_ (dashboard.87a613336d3da350da15.js?51e5438dd30d46f8ce40:126)
    at Ld (dashboard.87a613336d3da350da15.js?51e5438dd30d46f8ce40:126)
    at ki (dashboard.87a613336d3da350da15.js?51e5438dd30d46f8ce40:126)
    at Oi (dashboard.87a613336d3da350da15.js?51e5438dd30d46f8ce40:126)
hd @ dashboard.87a613336d3da350da15.js?51e5438dd30d46f8ce40:126
```

I don't know what the wrong data is - but the dashboard should not brick completely..

### Steps to reproduce the problem
1. don't know yet

### What I expected to happen
…

### Screenshots
<img width="1250" alt="Screenshot 2020-07-15 at 18 36 17" src="https://user-images.githubusercontent.com/7526174/87571956-1919bf80-c6cb-11ea-8fb4-da3feb18ef77.png">

**System information**
Operating system: 
Browser:

**Comment by JannikZed** [comment]
any idea maybe? I just have no idea, where the wrong data is and this feels important to the overall upgrade stability.

**Comment by maarcingebala** [comment]
I think it may be related to the "Activity" section which renders events. Maybe you have some event that is not associated with any user and the code tries to access user.email. We had a very similar issue on the order details page some time ago.

**Comment by JannikZed** [comment]
I could fix the problem by adding a user ID in the database table order_orderevent. 
Don't you think, Saleor should be resistant against such cases? You can easily simulate this problem:
- Create a user
- Create an order from draft
- Delete the user

Seems like a very normal case - when it is allowed to delete users, we should just not make this user field in the activity tab mandatory. When there is no user it could just show something like "none" 
 -> if you point me a little to the direction, I could add an RFC for that.

**Comment by maarcingebala** [comment]
The dashboard shouldn't break in such cases, it's definitely a bug.
