### ISSUE TITLE
Unable to edit product after creating it

### ISSUE THREAD

**Issue by IKarbowiak** [mirumee/saleor-dashboard#616]
### What I'm trying to achieve
I want to edit my product after creation.

### Steps to reproduce the problem
1. Go to the product section
2. Press `Create Product` button
3. Create Product just with name and Product Type
4. After creating, change the random field and press `Save`. Nothing happened.

### What I expected to happen
I want to be able to edit the product after creating it.

### Screenshots

Example of a product that cannot be changed.
![image](https://user-images.githubusercontent.com/40886528/87635639-b0205f00-c73f-11ea-91a4-2e8a3b036674.png)

**System information**
Operating system: 
Browser:

**Comment by krzysztofwolski** [comment]
Cant reproduce problem. Tested with current stable releases of saleor. Could be issue with local environment.
