### ISSUE TITLE
Nginx and Saleor configuration problems

### ISSUE THREAD

**Issue by umair-ilyas** [mirumee/saleor-dashboard#633]
When i am trying to login via dashboard, it shows me this error.
These are my exports in .bashrc file

 export ALLOWED_HOSTS=['192.168.0.102']
 export ALLOWED_CLIENT_HOSTS=192.168.0.102
 export DEBUG=True
 export SECRET_KEY=123456
 export INTERNAL_IPS=127.0.0.1,192.168.0.102,
 export DEFAULT_COUNTRY=IN
 export DEFAULT_CURRENCY=INR
 export APP_MOUNT_URI=/dashboard/
 export API_URI=http://192.168.0.102/graphql/

In the below screenshot why it is doing post request to localhost? As i already set API_URI in export on which my saleor instance is successfully running.

![Screenshot from 2020-08-07 10-07-09](https://user-images.githubusercontent.com/45622742/89611175-f3c93d00-d895-11ea-88be-b84290706cc7.png)

This is my nginx error logs:
2020/08/07 09:19:21 [alert] 8126#8126: aborting
2020/08/07 09:25:45 [alert] 8286#8286: *6 open socket #17 left in connection 7
2020/08/07 09:25:45 [alert] 8286#8286: aborting
2020/08/07 09:36:48 [error] 9158#9158: *3 connect() to unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: 192.168.0.102, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock:", host: "127.0.0.1"
2020/08/07 09:36:48 [error] 9158#9158: *3 connect() to unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: 192.168.0.102, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock:", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2020/08/07 09:36:51 [error] 9158#9158: *7 connect() to unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 192.168.0.102, server: 192.168.0.102, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock:", host: "192.168.0.102"
2020/08/07 09:36:57 [error] 9158#9158: *3 connect() to unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: 192.168.0.102, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock:", host: "127.0.0.1"
2020/08/07 09:36:57 [error] 9158#9158: *3 connect() to unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: 192.168.0.102, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock:", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2020/08/07 09:57:52 [alert] 10047#10047: *2 open socket #17 left in connection 7
2020/08/07 09:57:52 [alert] 10047#10047: aborting

This is my `etc/nginx/sites-available/saleorcore.conf:`
```
upstream django {
     server unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock fail_timeout=9000; # for a file socket
    #server 127.0.0.1:8080; # for a web port socket (we'll use this first)
}

server {
    listen      80;
    server_name 192.168.0.102; # substitute your machine's IP address or FQDN
    charset     utf-8;

    # max upload size
    client_max_body_size 75M;   # adjust to taste

    location /media  {
         alias /home/umair/PythonDjangoProjects/GitSaleor/media;  # your Django project's media files - amend as required
    }

    location /static {
        alias /home/umair/PythonDjangoProjects/GitSaleor/static; # your Django project's static files - amend as required
    }

    location / {
        uwsgi_pass  django;
        include     /home/umair/PythonDjangoProjects/GitSaleor/uwsgi_params;  # the uwsgi_params file you installed
    }
}

```
This is my etc/nginx/sites-available/dashboard:
```
server {
        listen 70;
        listen [::]:70;
        root /var/www/html/dashboard;
        index index.html;
        server_name 192.168.0.102;
        location / {
                try_files $uri $uri/ /index.html?$args;
        }
```

**System information**

Operating system: 
- [x] Ubuntu 18.04

Browser:
- [x] Chrome

**Comment by nalimhahs** [comment]
It looks like the socket file is missing or configured incorrectly. uWsgi by default is not running in the unix socket mode according to the config provided in saleor core. 

`uwsgi --ini saleor/wsgi/uwsgi.ini --enable-threads --socket /path/to/socket.sock --chmod-socket=666 --lazy --lazy-apps`

Use this command to run the server to create a socket file in the required path. If this is a permission issue, the `--chmod-socket=666` flag should solve it.

Also the location \ block you've used didn't quite work for me. I used the following block: 

`location / {
        uwsgi_pass  django;
        include     uwsgi_params; 
 }`

**Comment by umair-ilyas** [comment]
i am running saleor core by this command in the virtual environment
uwsgi --socket mysite.sock --module saleor.wsgi --chmod-socket=666
Did i have to update my saleorcore.conf -> upstream django?

**Comment by nalimhahs** [comment]
From what I'm seeing, this looks like a configuration issue with core, nothing wrong with the dashboard. When using the command I gave make sure you modify all the required paths. Check if the socket file exists in the directory where nginx is configured to look for it. 

If nginx is not throwing any errors, try going to the API_URI you specified in your browser. If the graphql playground is not showing up, it is probably something wrong with the nginx configuration. Check with port 8000 and see if now the graphql playground shows up? If not saleor core is probably not running or has crashed.

Also to clarify the `location /` block to modify was for the server not the dashboard.

**Comment by umair-ilyas** [comment]
My Store front is working on nginx now with same saleor core and products are showing in it
If everything is working on saleor store than it should also work on saleor dashboard

**Comment by umair-ilyas** [comment]
socket file is there but there appears a question mark on it
![Screenshot from 2020-08-07 13-53-15](https://user-images.githubusercontent.com/45622742/89628211-6990d100-d8b5-11ea-8667-9fc87ebb82f1.png)

**Comment by nalimhahs** [comment]
What is the API_URI used for both the storefront and dash? Are they different? Can nginx connect to the socket file now? Any errors in the nginx logs? What about the saleor core logs? Are any queries failing?

**Comment by umair-ilyas** [comment]
This is the current nginx error logs

2020/08/07 13:04:47 [error] 19195#19195: *7 connect() to unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 192.168.0.102, server: 192.168.0.102, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock:", host: "192.168.0.102", referrer: "http://192.168.0.102/"
2020/08/07 13:07:17 [error] 19468#19468: *1 connect() to unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 192.168.0.102, server: 192.168.0.102, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock:", host: "192.168.0.102"
2020/08/07 13:07:17 [error] 19468#19468: *1 connect() to unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 192.168.0.102, server: 192.168.0.102, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock:", host: "192.168.0.102", referrer: "http://192.168.0.102/"
2020/08/07 13:07:18 [error] 19468#19468: *1 connect() to unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 192.168.0.102, server: 192.168.0.102, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock:", host: "192.168.0.102"
2020/08/07 13:07:18 [error] 19468#19468: *1 connect() to unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 192.168.0.102, server: 192.168.0.102, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///home/umair/PythonDjangoProjects/GitSaleor/mysite.sock:", host: "192.168.0.102", referrer: "http://192.168.0.102/"
2020/08/07 13:09:47 [alert] 19468#19468: *8 open socket #17 left in connection 7
2020/08/07 13:09:47 [alert] 19468#19468: aborting
2020/08/07 13:12:03 [alert] 19600#19600: *24 open socket #18 left in connection 11
2020/08/07 13:12:03 [alert] 19600#19600: *21 open socket #17 left in connection 14
2020/08/07 13:12:03 [alert] 19600#19600: aborting

**Comment by umair-ilyas** [comment]
My API_URI is `export API_URI=http://192.168.0.102/graphql/`
but when i echo it on terminal it prints `http://192.168.0.102/graphql` without '/' after graphql and when i used this url on chrome it shows me successfull instance page not graphql page. And when i use the same url with '/' after graphql it shows me graphql page.
Is it the way it work?

**Comment by nalimhahs** [comment]
http://192.168.0.102/graphql/ is url which the dash should access. With the final /. Without it the endpoint is incorrect. This can be why it errors out. It should echo out the proper url.

**Comment by umair-ilyas** [comment]
If we consider this reason than how storefront is running because it also uses the same export. I also attached the two screenshot of it showing echo $API_URI and .bashrc file

![Screenshot from 2020-08-07 14-35-30](https://user-images.githubusercontent.com/45622742/89632355-7ca69f80-d8bb-11ea-99e7-98451deb2853.png)
![Screenshot from 2020-08-07 14-35-38](https://user-images.githubusercontent.com/45622742/89632358-7dd7cc80-d8bb-11ea-8f6b-e3798cff2286.png)

**Comment by umair-ilyas** [comment]
The main problem is this one i guess why dashboard is using localhost:8000/graphql while i am giving API_URI in .bashrc why he is not using that.

![Screenshot from 2020-08-07 14-38-37](https://user-images.githubusercontent.com/45622742/89632573-dad38280-d8bb-11ea-9394-43be29b0d34b.png)

**Comment by umair-ilyas** [comment]
Now i am getting this error of CORS. Can you please help me in this. This time no pop up show of saleor ran into an unexpected problem
![Screenshot from 2020-08-07 17-01-51](https://user-images.githubusercontent.com/45622742/89643819-052f3b00-d8d0-11ea-92e2-85d1c26d4bf0.png)
