### ISSUE TITLE
Dashboard > Configuration > Navigation > Footer

### ISSUE THREAD

**Issue by onelsonic** [mirumee/saleor-dashboard#648]
unable to create new item menu pointing to the homepage in the footer :
both using the relative path : /
or absolute path : https://www.mydomain.com

**Comment by maarcingebala** [comment]
What is the issue exactly? You can set any URL as a target for navigation items:
![image](https://user-images.githubusercontent.com/5421321/90368900-195eff00-e06b-11ea-913b-c8109b254beb.png)

**Comment by onelsonic** [comment]
Home will appear in the footer but the link will not work correctly in the Storefront.

Only the following is added and not the link:

`<span>Home</span>`

**Comment by onelsonic** [comment]
Alright so, apparently if we select the drop down list that appears below after typing a custom URL, then save, it works.

But just typing the URL, then Saving, does not work.

Current UI practice is : "you type and then no need to save."
A drop down list can be used to select from existing data, but when entering new custom data, a drop down list is really confusing from an UI perspective. A strange behaviour, but works when we know the trick...
