### ISSUE TITLE
Updating or creating addresses generates two queries

### ISSUE THREAD

**Issue by mateuszkula** [mirumee/saleor-dashboard#65]
### What I'm trying to achieve
Adding new address for customer will produce two addresses if phone number is wrong.

### Screenshots

![Kapture 2019-07-09 at 10 13 46](https://user-images.githubusercontent.com/30259869/60871094-6189dc00-a232-11e9-8f5a-7172058b7b65.gif)

**System information**
Operating system: MacOSX
Browser: Firefox

**Comment by dominik-zeglen** [comment]
Seems to be fixed some time ago, since I can no longer reproduce this locally. Please reopen this issue if the problem still exists using newest dashboard and core versions.
