### ISSUE TITLE
Access private User metadata through dashboard

### ISSUE THREAD

**Issue by salwator** [mirumee/saleor-dashboard#66]
### What I'm trying to achieve
After introducing private metadata to _User_ model there might be need for staff to edit/delete/add metadata manually.

### Describe a proposed solution
Component to access metadata for _User_ and other future objects with meta.

**Comment by maarcingebala** [comment]
I think we can close this one sine we also have #195, which talks about the same issue - having a UI for metadata in the dashboard.
