### ISSUE TITLE
Placeholder "Search... " is only visible if focus is set to field search.

### ISSUE THREAD

**Issue by zlosliwa** [mirumee/saleor-dashboard#666]
### What I'm trying to achieve
Placeholder "Search ..." is only visible if focus is set to the field search, so it is not clear that this field is there. 

### Steps to reproduce the problem
1. Log in as an Admin to Dashboard.
2. Go to page where search is available e.g. **Products**
3. Move mouse to the field with search
4. Placeholder is shown after step no. 3.

### What I expected to happen
Placeholder "Search... " should be visible when focus is not set on this field or the loupe should be shown.

### Screenshots

![image](https://user-images.githubusercontent.com/29308910/90922600-90d6ba80-e3ec-11ea-8b7d-5ec1ceac748d.png)
![image](https://user-images.githubusercontent.com/29308910/90922614-9502d800-e3ec-11ea-8cb1-14780c3a97f8.png)

**System information**

Operating system: 
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [x] Other

**Comment by krzysztofwolski** [comment]
Fixed
