### ISSUE TITLE
npm run build is taking a while to complete

### ISSUE THREAD

**Issue by GeraldAburto** [mirumee/saleor-dashboard#700]
### What I'm trying to achieve
Generate build

### Steps to reproduce the problem
1. run in terminal: npm run build

### What I expected to happen
The build generates successfully

### Screenshots
![image](https://user-images.githubusercontent.com/7727225/92498109-74da6380-f1b7-11ea-9036-86ea05ac29cc.png)

### Console output

```
$ npm run build

> saleor-dashboard@2.10.1 build E:\Projects\mascool-dashboard
> webpack -p

Starting type checking service...
Using 1 worker with 2048MB memory limit
```

**System information**

Operating system: 
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

**Comment by theIYD** [comment]
This happens on an EC2 with t2 medium instance type. Cannot figure it out
