### ISSUE TITLE
Customers can log into Dashboard

### ISSUE THREAD

**Issue by cyberdemic** [mirumee/saleor-dashboard#734]
### What I'm trying to achieve
If a customer tries to log into the Dashboard, deny access.

### Steps to reproduce the problem
1. Create a customer on the storefront
2. Log into dashboard with new user

### What I expected to happen
Access to be denied.

### Screenshots
![dashboard-login-customer](https://user-images.githubusercontent.com/54118049/94473971-cb690b00-0181-11eb-9aca-815d14af46e4.png)

**Still shows catalog information using search function in dashboard with testuser**
![unauthorized-catalog-search](https://user-images.githubusercontent.com/54118049/94474832-12a3cb80-0183-11eb-9550-3827fe86951a.png)

**System information**

Operating system: 
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [x] Chrome
- [ ] Edge
- [x] Firefox
- [ ] Other

**Comment by karolkielecki** [comment]
@cyberdemic Thanks for reporting! We are aware of this issue. We will fix it as soon as we can.

**Comment by eCzerniak** [comment]
Fixed on 3.0
