### ISSUE TITLE
User flow when adding variant attributes can be improved

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor-dashboard#85]
### What I'm trying to achieve
With the new enterprise grade attributes, when adding a variant attribute to a product type, the flow goes like so.
1. Check "This product type has variants"
2. Click "Save"
3. Click "Add Variant Attribute"
4. Maybe click "Save" again?

The main issue is with step 2. It's not clear to the user that they have to save before trying to add variant attribute. By convention, "save" is usually clicked after we've finished editing a form, not after each field.

### Describe a proposed solution
This is admittedly very tricky. Maybe propose to save the changes when user attempts to add variant attributes? Or even better, only add the attribute when "save" is clicked in the product type form.

### Other solutions I've tried and won't work
Automatically saving the product type without user consent can cause even more confusion for the user. For example, they might click "cancel" and expect that no modifications have been made to the product type.

**Comment by maarcingebala** [comment]
@dominik-zeglen Could you share the suggested way of fixing this?

**Comment by maarcingebala** [comment]
Fixed in #152
