### ISSUE TITLE
Buttons to delete are called Delete and Remove. Need to be unified.

### ISSUE THREAD

**Issue by MonikaMrozek** [mirumee/saleor-dashboard#86]
### What I'm trying to achieve
We should either use Delete or Remove and be consistent throughout the application. 

### Screenshots
![image](https://user-images.githubusercontent.com/53564363/62773067-811a5b80-baa1-11e9-8572-c110e5e8267b.png)

Which one we should use? Your thoughts? @timcla  @pwgryglak

**Comment by pwgryglak** [comment]
@MonikaMrozek 
Thanks for sharing the definition. I admit this is a error on my part. I've updated the project to be consistent with the naming.

**Comment by patrys** [comment]
Here's a "danger" dialog from GitHub (no, I did not remove Saleor):

![image](https://user-images.githubusercontent.com/81205/62856744-0007d200-bcf6-11e9-8a6e-acff90ca73c2.png)

**Comment by MonikaMrozek** [comment]
Guys, we need to decide something. 
I suggest using the Delete button in all cases. If we adopt this, all existing buttons called Remove should then be changed to Delete buttons. 
To be fair, I take any solution, as long as we use one ;)

**Comment by pwgryglak** [comment]
On whole design I've changed the button to delete. I think it is best based on what you've found regarding definitions of the two words.
