### ISSUE TITLE
Naming convention: Add X / Create X

### ISSUE THREAD

**Issue by MonikaMrozek** [mirumee/saleor-dashboard#87]
### What I'm trying to achieve
1. We have places in the dashboard where we are not consistent with the naming convention.
The button to create a record is called Create Order and in other page it is Add Customer.

 Shall we stick to one? For example Add X/ Add Customer/ Voucher etc.

2. The other thing is that we should be consistent in UI strings from one page to another:
I click button: Add Sale but I am readirected to a page called Create Sale. 
Shall we keep it consistent, so the next page would be Add Sale?

### Screenshots
![image](https://user-images.githubusercontent.com/53564363/62775577-52ec4a00-baa8-11e9-95fc-2bbc071f3459.png)

![image](https://user-images.githubusercontent.com/53564363/62775596-5ed80c00-baa8-11e9-9e0e-6f93e8b939b5.png)

![image](https://user-images.githubusercontent.com/53564363/62776232-3ea94c80-baaa-11e9-8464-417c40cf1cf1.png)
leading up to page called:

![image](https://user-images.githubusercontent.com/53564363/62776253-4c5ed200-baaa-11e9-9c2a-dfd4f9f9cef4.png)

**Comment by MonikaMrozek** [comment]
I would think more of a solution when we actually pick one and have only one throughout the dashboard. Like we did with the Remove/Delete. 
As Tim noted, it sounds better to add a person than to 'create' one ;)
And it also sounds good when you add order or add sale.

What do you think?

**Comment by pwgryglak** [comment]
@timcla @MonikaMrozek 

We can create/add those things:
- Products
- Categories
- Collection
- Customers
- Sales
- Vouchers
- Gift Cards (Now its called "Issue Gift Card")
- Page
- Menu 
- Menu Items
- Orders
- Staff Members (I think we should use invite here)
- Shipping Zone 
- Rates
- Product Type
- Attribute
- Value
- Subcategory (there is this thing that circles above our head which is dropping categories)
- Address
- Authentication Key
- Order Tracking

That's about it. 

About @patrys question "plus icons" are not required to be there and we can remove them if we think that is the best idea.

**Comment by MonikaMrozek** [comment]
I think this is the question someone touched before (sorry, I don't remeber who :( ), if we are adding someting (to a collection, for example) or if we a creating a new record. So: Create Product (if it is a new record) or Add Product to collection (where this action will touch the existing product record).
Similarly it will happen with Attributes? Correct me if I am wrong, but most probably we first have to Create Attribute, and only then Add Attribute to Product? Right? 
Or shall we just write Add Product when creating a new one and Add Product to Collection when additng to some specified collction?

**Comment by patrys** [comment]
It was I, Leclerc: https://saleor.atlassian.net/browse/CORE-1258

**Comment by MonikaMrozek** [comment]
OK, I think we've reached some good compromise proposed by Paweł. All good :)

**Comment by pwgryglak** [comment]
Our compromise is:

- Set all elements creating new records to: Create - on modals also. With some exceptions: Issue a gift card, Invite Staff, add address.

- All elements that assign (add records to something) - Buttons will be changed to assign -> Assign Products, Assign Countries etc. exception adding products to draft orders

**Comment by timcla** [comment]
> Our compromise is:
> 
> * Set all elements creating new records to: Create - on modals also. With some exceptions: Issue a gift card, Invite Staff, add address.
> * All elements that assign (add records to something) - Buttons will be changed to assign -> Assign Products, Assign Countries etc. exception adding products to draft orders

Yes, this is what I was going to write just now. I would also say that 'Add Customer', as Create sounds a bit weird there. For people I would always 'Add'

**Comment by dominik-zeglen** [comment]
Fixed in #166
