### ISSUE TITLE
If no channels exist, the dashboard doesn't load  

### ISSUE THREAD

**Issue by LeOndaz** [mirumee/saleor-dashboard#900]
As the title suggests, if there're no channels, the dashboard doesn't load and the console is filled with errors, this case should be handled and if no channels exist, the admin is redirected to create one from the dashboard.

**Comment by sagital** [comment]
Ran into the same issue on a clean install. I think there should be a way to create a default channel from either the dashboard or the `manage.py` script in the API

**Comment by LeOndaz** [comment]
@sagital There should be an option in the dashboard itself

**Comment by sagital** [comment]
Yes, problem being you can't get there if there is no channel set yet.

**Comment by LeOndaz** [comment]
Not stale

**Comment by krzysztofwolski** [comment]
We had regression bug with no channels situation, currently it should be resolved.
