### ISSUE TITLE
Add link Button

### ISSUE THREAD

**Issue by pwgryglak** [mirumee/saleor-dashboard#92]
I've encountered a bug.
Button color on modal for adding link to text in Draftail is unreadable in dark theme.
It also has wrong color

Screenshot:
<img width="350" alt="Screen Shot 2019-08-12 at 11 03 35" src="https://user-images.githubusercontent.com/40759237/62854927-12cbd800-bcf1-11e9-94e1-2ae4aeb64e90.png">

**Comment by Jc7j** [comment]
Ill try and take this!

**Comment by krzysztofwolski** [comment]
We are no longer using draftail
