### ISSUE TITLE
Assign warehouse errors 

### ISSUE THREAD

**Issue by LeOndaz** [mirumee/saleor-dashboard#941]
Just try to create a variant and assign a warehouse, the dashboard blows up

**Comment by maarcingebala** [comment]
Please use the issue template and provide exact steps to reproduce the issue, in particular in which version of Saleor you're experiencing it.

**Comment by LeOndaz** [comment]
The steps are as I said:
1) Create a variant
2) Assign a warehouse
3) Dashboard explodes (woops, an error ...)
and on both saleor and the dashboard, I use the master branch
