### ISSUE TITLE
Update documentation about enabling the usage of Draftail in storefront 1.0

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-dashboard#95]
Users using the dashboard 2.0 on the storefront 1.0 should set the `USE_JSON` environment variable to `True`.

We should add this note to the README or in the documentation.

**Comment by raoz** [comment]
The variable name is USE_JSON_CONTENT

**Comment by NyanKiyoshi** [comment]
Not sure how that will go for documenting as it is for storefront 1.0? @maarcingebala
