### ISSUE TITLE
Missing save button after collection update in dashboard product detail page

### ISSUE THREAD

**Issue by tilman** [mirumee/saleor-dashboard#976]
### What I'm trying to achieve
save product if collection gets changed

### Steps to reproduce the problem
1. open the product detail page in the dashboard
2. change a collection on the side
3. no "SAVE" bin appears => as a user I then think it was auto saved
4. reload the page. The new collections are gone

(As a workaround I now add a character to the title and remove it again to make the SAVE button appear. But this should not be the solution.)

### What I expected to happen
Auto save the collections or make the SAVE button visible

**Comment by krzysztofwolski** [comment]
Fixed by #987
